import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:zapsafe_mobile/data/services/crowd_panic_detector.dart';
import 'package:zapsafe_mobile/data/services/mel_spectrogram.dart';

/// Day 265 — parity tests for `s_crowd_panic`'s preprocessing, the first
/// two-input (audio + IMU fusion) model wired in this app.
///
/// Checked against real output, not reimplemented on faith:
///
///  1. The mel side's `power_to_db(mel, ref=np.max)` **without** the
///     per-clip min-max rescale m1/mg_gunshot use — this model's own
///     `audio_to_mel` (`day95_s_crowd_panic.py`) skips that step and relies
///     on a separate *global* mean/std instead. `MelSpectrogram.compute(...,
///     normalize: false)` was added specifically for this — the parity
///     fixture (`test/fixtures/s_crowd_panic_mel_golden.json`, generated by
///     real librosa 0.11.0, not assumed) is what proves the `normalize:
///     false` path is really skipping min-max and not silently doing it
///     anyway.
///  2. The real `s_crowd_panic_norm.json` asset loads with the exact
///     mel_mean/mel_std/imu_mean/imu_std the retrained model actually
///     shipped with (read from the bundled asset file directly, not
///     hardcoded here — a future retrain that changes these constants
///     should not require a code change to this test).
///  3. The global per-channel IMU normalisation arithmetic
///     (`(x - imu_mean[c]) / imu_std[c]`) against hand-computed values.
void main() {
  Float64List toneSignal({int sr = 16000, double seconds = 2.0}) {
    final n = (sr * seconds).round();
    final y = Float64List(n);
    for (var i = 0; i < n; i++) {
      final t = i / sr;
      y[i] = 0.5 * math.sin(2 * math.pi * 440 * t) +
          0.25 * math.sin(2 * math.pi * 1720 * t);
    }
    return y;
  }

  group('MelSpectrogram at s_crowd_panic params (normalize: false)', () {
    late Map<String, dynamic> golden;

    setUpAll(() {
      final f = File('test/fixtures/s_crowd_panic_mel_golden.json');
      golden = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    });

    test('shape matches librosa for a real 2s/16kHz clip before padding', () {
      final mel = MelSpectrogram(
        sampleRate: 16000,
        nFft: 2048,
        hopLength: 512,
        nMels: 64,
        fmax: 8000,
      ).compute(toneSignal(), normalize: false);
      expect(mel.length, 64);
      expect(mel[0].length, 63,
          reason: '1 + 32000 ~/ 512 = 63 frames at 16kHz/2.0s — under the '
              '64-wide target, so audio_to_mel zero-pads by 1 column '
              '(not np.resize/wrap, unlike mg_gunshot).');
      expect((golden['mel_shape_before_pad'] as List), [64, 63]);
    });

    test('matches real librosa power_to_db(ref=max) elementwise, no '
        'min-max rescale applied (after the same zero-pad audio_to_mel '
        'applies, since the golden fixture was captured post-pad)', () {
      final raw = MelSpectrogram(
        sampleRate: 16000,
        nFft: 2048,
        hopLength: 512,
        nMels: 64,
        fmax: 8000,
      ).compute(toneSignal(), normalize: false);
      final mel = MelSpectrogram.fitFrames(raw, 64); // zero-pad 63 -> 64 cols

      void compareRow(String key, int row) {
        final expected = (golden[key] as List).cast<num>();
        for (var i = 0; i < expected.length; i++) {
          expect(mel[row][i], closeTo(expected[i].toDouble(), 1e-4),
              reason: '$key[$i] diverged from real librosa power_to_db');
        }
      }

      compareRow('row0', 0);
      compareRow('row32', 32);
      compareRow('row63', 63);

      final col = (golden['col15'] as List).cast<num>();
      for (var m = 0; m < col.length; m++) {
        expect(mel[m][15], closeTo(col[m].toDouble(), 1e-4),
            reason: 'col15[$m] diverged from real librosa power_to_db');
      }
    });

    test('overall mean matches librosa (still in raw dB range, not [0,1] '
        '— proves normalize:false really skips the per-clip min-max)', () {
      final raw = MelSpectrogram(
        sampleRate: 16000,
        nFft: 2048,
        hopLength: 512,
        nMels: 64,
        fmax: 8000,
      ).compute(toneSignal(), normalize: false);
      final mel = MelSpectrogram.fitFrames(raw, 64);
      var sum = 0.0, count = 0;
      for (final row in mel) {
        for (final v in row) {
          sum += v;
          count++;
        }
      }
      final mean = sum / count;
      expect(mean, closeTo((golden['mel_mean'] as num).toDouble(), 1e-3));
      // The default (normalize: true) path always lands in [0, 1]; a real
      // dB-scale mean here (large negative) is the structural proof the two
      // paths are genuinely different, not just parameterised the same way.
      expect(mean, lessThan(-1.0));
    });

    test('default normalize:true still returns [0,1] (existing m1/mg_gunshot '
        'callers are unaffected by the new parameter)', () {
      final mel = MelSpectrogram(
        sampleRate: 16000,
        nFft: 2048,
        hopLength: 512,
        nMels: 64,
        fmax: 8000,
      ).compute(toneSignal());
      for (final row in mel) {
        for (final v in row) {
          expect(v, inInclusiveRange(0.0, 1.0));
        }
      }
    });
  });

  group('s_crowd_panic_norm.json — real bundled asset', () {
    late Map<String, dynamic> norm;

    setUpAll(() {
      final f = File('assets/models/s_crowd_panic_norm.json');
      norm = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    });

    test('has the real 6-channel imu_mean/imu_std and scalar mel_mean/std',
        () {
      expect(norm['mel_h'], 64);
      expect(norm['mel_w'], 64);
      expect(norm['imu_len'], 128);
      expect((norm['imu_mean'] as List).length, 6);
      expect((norm['imu_std'] as List).length, 6);
      expect(norm['mel_mean'], isA<num>());
      expect(norm['mel_std'], isA<num>());
    });
  });

  group('CrowdPanicDetector preprocessing (pure Dart, no interpreter)', () {
    test('melFeaturesFromPcm produces a flattened 64x64 float array, '
        'globally mean/std normalised', () {
      final det = _CrowdPanicPreprocOnly();
      final feats = det.melFeaturesFromPcm(toneSignal());
      expect(feats.length, 64 * 64);
      for (final v in feats) {
        expect(v.isFinite, isTrue);
      }
    });

    test('imuFeaturesFromWindow applies (x - imu_mean[c]) / imu_std[c] per '
        'channel', () {
      final det = _CrowdPanicPreprocOnly();
      final window =
          List<List<double>>.generate(128, (_) => [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]);
      final feats = det.imuFeaturesFromWindow(window);
      expect(feats.length, 128 * 6);
      for (var c = 0; c < 6; c++) {
        final expected =
            (window[0][c] - det.imuMean[c]) / det.imuStd[c];
        // 1e-6, not 1e-9: feats is Float32List (single precision), expected
        // is computed in double precision.
        expect(feats[c], closeTo(expected, 1e-6));
      }
    });

    test('imuFeaturesFromWindow rejects a window of the wrong length', () {
      final det = _CrowdPanicPreprocOnly();
      expect(
          () => det.imuFeaturesFromWindow(
              List<List<double>>.generate(50, (_) => [0, 0, 0, 0, 0, 0])),
          throwsArgumentError);
    });
  });
}

/// Test-only helper mirroring `CrowdPanicDetector`'s pure preprocessing
/// (`melFeaturesFromPcm`, `imuFeaturesFromWindow`) without needing a loaded
/// native interpreter — same pattern `gunshot_detector_test.dart`'s
/// `GunshotDetectorV2Testable` uses, since `CrowdPanicDetector`'s
/// constructor is private and gated behind `tryLoad()`.
class _CrowdPanicPreprocOnly {
  final MelSpectrogram _mel = MelSpectrogram(
    sampleRate: CrowdPanicDetector.kSampleRate,
    nFft: 2048,
    hopLength: 512,
    nMels: CrowdPanicDetector.kMelH,
    fmax: 8000,
  );

  // Real constants from the bundled s_crowd_panic_norm.json (Day 264 kernel
  // v2 export) — kept in sync manually here since this helper deliberately
  // avoids touching rootBundle/asset loading (unavailable outside a widget
  // test harness).
  final double melMean = -16.59919548034668;
  final double melStd = 17.935195922851562;
  final List<double> imuMean = const [
    8.82717227935791,
    1.4601374864578247,
    2.152517795562744,
    -0.6515188813209534,
    0.10683828592300415,
    2.0018808841705322,
  ];
  final List<double> imuStd = const [
    15.887107849121094,
    4.157863616943359,
    4.65611457824707,
    2.367788314819336,
    0.8089812397956848,
    4.004110813140869,
  ];

  Float32List melFeaturesFromPcm(Float64List pcm) {
    const n = CrowdPanicDetector.kAudioSamples;
    final clip = pcm.length == n
        ? pcm
        : (Float64List(n)
          ..setRange(0, math.min(pcm.length, n),
              pcm.length < n ? pcm : pcm.sublist(0, n)));
    final rawMel = _mel.compute(clip, normalize: false);
    final fitted = MelSpectrogram.fitFrames(rawMel, CrowdPanicDetector.kMelW);

    final out = Float32List(CrowdPanicDetector.kMelH * CrowdPanicDetector.kMelW);
    var i = 0;
    for (var h = 0; h < CrowdPanicDetector.kMelH; h++) {
      final row = fitted[h];
      for (var w = 0; w < CrowdPanicDetector.kMelW; w++) {
        out[i++] = (row[w] - melMean) / melStd;
      }
    }
    return out;
  }

  Float32List imuFeaturesFromWindow(List<List<double>> samples) {
    if (samples.length != CrowdPanicDetector.kImuWindow) {
      throw ArgumentError('wrong window length');
    }
    final out =
        Float32List(CrowdPanicDetector.kImuWindow * CrowdPanicDetector.kImuChannels);
    var i = 0;
    for (var t = 0; t < CrowdPanicDetector.kImuWindow; t++) {
      final row = samples[t];
      for (var c = 0; c < CrowdPanicDetector.kImuChannels; c++) {
        out[i++] = (row[c] - imuMean[c]) / imuStd[c];
      }
    }
    return out;
  }
}
