import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:zapsafe_mobile/data/services/aggressive_speech_features.dart';
import 'package:zapsafe_mobile/data/services/vocal_stress_features.dart';
import 'package:zapsafe_mobile/data/services/yin_pitch.dart';

/// Day 352 — parity for the 2048/512 prosodic path `h_aggressive_v4_38`
/// needs.
///
/// The golden fixture is generated by **the same Python `features38()` that
/// produced v4's training data** (`work/h_aggressive_v4/make_golden.py`), so
/// a mismatch here is a Dart bug rather than a disagreement about the spec.
///
/// Why this test is load-bearing: three shipped models now share `[1,38]`
/// across **two** feature definitions, and feeding the wrong one produces
/// the right shape with a wrong answer. `m4_vocal_stress_en_38` reported
/// DEAD at a constant 1.0 when the gate handed it the `librosa.pyin`
/// fixture — a domain mismatch dressed as a dead model. Nothing in
/// `flutter test` can execute a .tflite, so feature parity is the only
/// thing the Dart suite *can* verify, and it is therefore the only guard
/// against that failure.
void main() {
  Float64List tone({double seconds = 3.0}) {
    const sr = AggressiveSpeechFeatures.kSampleRate;
    final n = (sr * seconds).round();
    final y = Float64List(n);
    for (var i = 0; i < n; i++) {
      final t = i / sr;
      y[i] = 0.5 * math.sin(2 * math.pi * 220 * t) +
          0.25 * math.sin(2 * math.pi * 660 * t);
    }
    return y;
  }

  late Map<String, dynamic> golden;

  setUpAll(() {
    golden = jsonDecode(
        File('test/fixtures/h_aggressive_v4_golden.json').readAsStringSync())
        as Map<String, dynamic>;
  });

  group('contract', () {
    test('analyses at 2048/512, NOT m4/m5\'s 512/256', () {
      expect(AggressiveSpeechFeatures.kNFft, 2048);
      expect(AggressiveSpeechFeatures.kHopLength, 512);
      expect(AggressiveSpeechFeatures.kSampleRate, 16000);
      expect(AggressiveSpeechFeatures.kSamples, 48000);
      expect(AggressiveSpeechFeatures.kFeatureDim, 38);

      // The point of this assertion is the DIFFERENCE. If these ever match,
      // one of the two models is being fed the other's features.
      expect(AggressiveSpeechFeatures.kNFft,
          isNot(equals(VocalStressFeatures.kNFft)));
      expect(AggressiveSpeechFeatures.kHopLength,
          isNot(equals(VocalStressFeatures.kHopLength)));
    });

    test('the fixture was generated at those same params', () {
      expect(golden['frame'], AggressiveSpeechFeatures.kNFft);
      expect(golden['hop'], AggressiveSpeechFeatures.kHopLength);
      expect(golden['sr'], AggressiveSpeechFeatures.kSampleRate);
    });

    test('YinPitch defaults still belong to m4/m5, untouched', () {
      // Day 352 parameterised YinPitch rather than changing its constants.
      // If these drift, m4 and m5 silently start receiving 2048-frame
      // pitch features.
      expect(YinPitch.kFrameLength, 512);
      expect(YinPitch.kHopLength, 256);
    });
  });

  group('parity with the v4 trainer', () {
    test('every case matches the Python extractor', () {
      final f = AggressiveSpeechFeatures();
      final cases = golden['cases'] as Map<String, dynamic>;

      final signals = <String, Float64List>{
        'tone': tone(),
        'silence': Float64List(AggressiveSpeechFeatures.kSamples),
        'short': tone(seconds: 0.4),
      };

      for (final entry in signals.entries) {
        final want = (cases[entry.key] as List).cast<num>();
        final got = f.compose38(entry.value);
        expect(got.length, 38, reason: entry.key);
        for (var i = 0; i < 38; i++) {
          // Absolute tolerance scaled by magnitude: MFCC values run to
          // -1131, pitch to 220, shimmer to 1e-3, so a single epsilon
          // would be either vacuous or impossible.
          final expected = want[i].toDouble();
          final tol = math.max(1e-4, expected.abs() * 2e-3);
          expect(got[i], closeTo(expected, tol),
              reason: '${entry.key} feature[$i]');
        }
      }
    });

    test('a 220 Hz tone is tracked at 220 Hz', () {
      final got = AggressiveSpeechFeatures().compose38(tone());
      expect(got[1], closeTo(220.0, 1.0), reason: 'f0_mean');
      expect(got[0], greaterThan(0.9), reason: 'voiced fraction');
      expect(got[6], greaterThan(0.9), reason: 'hnr on a periodic signal');
    });

    test('noise is unvoiced and silence does not divide by zero', () {
      final f = AggressiveSpeechFeatures();
      final silence = f.compose38(Float64List(
          AggressiveSpeechFeatures.kSamples));
      expect(silence[0], 0.0, reason: 'no voiced frames in silence');
      expect(silence[1], 0.0, reason: 'f0_mean zeroes rather than NaN');
      expect(silence[5], 0.0, reason: 'shimmer');
      for (final v in silence) {
        expect(v.isFinite, isTrue);
      }
    });
  });

  group('the two 38-vectors are genuinely different', () {
    test('same signal, different features', () {
      final wide = AggressiveSpeechFeatures().compose38(tone());
      final narrow = VocalStressFeatures().compose38(tone());
      expect(wide.length, narrow.length,
          reason: 'same shape is exactly why this is dangerous');

      var differing = 0;
      for (var i = 0; i < 38; i++) {
        if ((wide[i] - narrow[i]).abs() > 1e-6) differing++;
      }
      // If these vectors were interchangeable the whole separate class
      // would be unnecessary; the measured cost of confusing them is
      // 0.6661 -> 0.5918 on natural speech (Day 351).
      expect(differing, greaterThan(20),
          reason: 'the windows must produce materially different vectors');
    });
  });

  group('clip fitting', () {
    test('short input is zero-padded to exactly 3 s', () {
      final got = AggressiveSpeechFeatures().compose38(tone(seconds: 0.4));
      expect(got.length, 38);
      for (final v in got) {
        expect(v.isFinite, isTrue);
      }
    });

    test('long input is truncated, matching a 3 s clip', () {
      final f = AggressiveSpeechFeatures();
      final long = f.compose38(tone(seconds: 6.0));
      final exact = f.compose38(tone(seconds: 3.0));
      for (var i = 0; i < 38; i++) {
        expect(long[i], closeTo(exact[i], 1e-9), reason: 'feature[$i]');
      }
    });
  });
}
