/// Route catalogue for Day 289 full regression runner.
/// Auto-derived from [AppRoutes] in app_router.dart.
part of 'day289_full_regression_runner_screen.dart';

const kRouteRows = [
  RouteRow(id: 'r1', title: 'onboarding', dayRef: 'onboarding', section: 'Core', route: AppRoutes.onboarding),
  RouteRow(id: 'r2', title: 'dashboard', dayRef: 'dashboard', section: 'Core', route: AppRoutes.dashboard),
  RouteRow(id: 'r3', title: 'sos Active', dayRef: 'sosActive', section: 'Core', route: AppRoutes.sosActive),
  RouteRow(id: 'r4', title: 'vault', dayRef: 'vault', section: 'Core', route: AppRoutes.vault),
  RouteRow(id: 'r5', title: 'contacts', dayRef: 'contacts', section: 'Core', route: AppRoutes.contacts),
  RouteRow(id: 'r6', title: 'settings', dayRef: 'settings', section: 'Core', route: AppRoutes.settings),
  RouteRow(id: 'r7', title: 'day1', dayRef: 'Day 1', section: 'Foundation', route: AppRoutes.day1),
  RouteRow(id: 'r8', title: 'day9', dayRef: 'Day 9', section: 'Foundation', route: AppRoutes.day9),
  RouteRow(id: 'r9', title: 'day10', dayRef: 'Day 10', section: 'Foundation', route: AppRoutes.day10),
  RouteRow(id: 'r10', title: 'day6', dayRef: 'day6', section: 'Core', route: AppRoutes.day6),
  RouteRow(id: 'r11', title: 'phone Entry', dayRef: 'phoneEntry', section: 'Core', route: AppRoutes.phoneEntry),
  RouteRow(id: 'r12', title: 'otp Verify', dayRef: 'otpVerify', section: 'Core', route: AppRoutes.otpVerify),
  RouteRow(id: 'r13', title: 'permissions', dayRef: 'permissions', section: 'Core', route: AppRoutes.permissions),
  RouteRow(id: 'r14', title: 'device Tier', dayRef: 'deviceTier', section: 'Core', route: AppRoutes.deviceTier),
  RouteRow(id: 'r15', title: 'onboarding Permissions', dayRef: 'onboardingPermissions', section: 'Core', route: AppRoutes.onboardingPermissions),
  RouteRow(id: 'r16', title: 'feature Flags', dayRef: 'featureFlags', section: 'Core', route: AppRoutes.featureFlags),
  RouteRow(id: 'r17', title: 'week3 Review', dayRef: 'week3Review', section: 'Core', route: AppRoutes.week3Review),
  RouteRow(id: 'r18', title: 'push Notifications', dayRef: 'pushNotifications', section: 'Core', route: AppRoutes.pushNotifications),
  RouteRow(id: 'r19', title: 'push Routing', dayRef: 'pushRouting', section: 'Core', route: AppRoutes.pushRouting),
  RouteRow(id: 'r20', title: 'drills Schedule', dayRef: 'drillsSchedule', section: 'Core', route: AppRoutes.drillsSchedule),
  RouteRow(id: 'r21', title: 'month1 Integration', dayRef: 'month1Integration', section: 'Core', route: AppRoutes.month1Integration),
  RouteRow(id: 'r22', title: 'month1 Review', dayRef: 'month1Review', section: 'Core', route: AppRoutes.month1Review),
  RouteRow(id: 'r23', title: 'background Engine', dayRef: 'backgroundEngine', section: 'Core', route: AppRoutes.backgroundEngine),
  RouteRow(id: 'r24', title: 'watchdog', dayRef: 'watchdog', section: 'Core', route: AppRoutes.watchdog),
  RouteRow(id: 'r25', title: 'platform Channels', dayRef: 'platformChannels', section: 'Core', route: AppRoutes.platformChannels),
  RouteRow(id: 'r26', title: 'lp4 Watchdog', dayRef: 'lp4Watchdog', section: 'Core', route: AppRoutes.lp4Watchdog),
  RouteRow(id: 'r27', title: 'week5 Review', dayRef: 'week5Review', section: 'Core', route: AppRoutes.week5Review),
  RouteRow(id: 'r28', title: 'audio Capture', dayRef: 'audioCapture', section: 'Core', route: AppRoutes.audioCapture),
  RouteRow(id: 'r29', title: 'audio Features', dayRef: 'audioFeatures', section: 'Core', route: AppRoutes.audioFeatures),
  RouteRow(id: 'r30', title: 'ios Audio', dayRef: 'iosAudio', section: 'Core', route: AppRoutes.iosAudio),
  RouteRow(id: 'r31', title: 'inference', dayRef: 'inference', section: 'Core', route: AppRoutes.inference),
  RouteRow(id: 'r32', title: 'week6 Review', dayRef: 'week6Review', section: 'Core', route: AppRoutes.week6Review),
  RouteRow(id: 'r33', title: 'tflite Models', dayRef: 'tfliteModels', section: 'Core', route: AppRoutes.tfliteModels),
  RouteRow(id: 'r34', title: 'dcs Engine', dayRef: 'dcsEngine', section: 'Core', route: AppRoutes.dcsEngine),
  RouteRow(id: 'r35', title: 'dcs Stream', dayRef: 'dcsStream', section: 'Core', route: AppRoutes.dcsStream),
  RouteRow(id: 'r36', title: 'isolate Latency', dayRef: 'isolateLatency', section: 'Core', route: AppRoutes.isolateLatency),
  RouteRow(id: 'r37', title: 'week7 Review', dayRef: 'week7Review', section: 'Core', route: AppRoutes.week7Review),
  RouteRow(id: 'r38', title: 'imu Service', dayRef: 'imuService', section: 'Core', route: AppRoutes.imuService),
  RouteRow(id: 'r39', title: 'gps Service', dayRef: 'gpsService', section: 'Core', route: AppRoutes.gpsService),
  RouteRow(id: 'r40', title: 'day38 Fallback And State', dayRef: 'day38FallbackAndState', section: 'Core', route: AppRoutes.day38FallbackAndState),
  RouteRow(id: 'r41', title: 'day39 State Wiring', dayRef: 'day39StateWiring', section: 'Core', route: AppRoutes.day39StateWiring),
  RouteRow(id: 'r42', title: 'month2 Review', dayRef: 'month2Review', section: 'Core', route: AppRoutes.month2Review),
  RouteRow(id: 'r43', title: 'onboarding Step1', dayRef: 'onboardingStep1', section: 'Core', route: AppRoutes.onboardingStep1),
  RouteRow(id: 'r44', title: 'onboarding Step2', dayRef: 'onboardingStep2', section: 'Core', route: AppRoutes.onboardingStep2),
  RouteRow(id: 'r45', title: 'onboarding Step3', dayRef: 'onboardingStep3', section: 'Core', route: AppRoutes.onboardingStep3),
  RouteRow(id: 'r46', title: 'onboarding Step4', dayRef: 'onboardingStep4', section: 'Core', route: AppRoutes.onboardingStep4),
  RouteRow(id: 'r47', title: 'onboarding Step5', dayRef: 'onboardingStep5', section: 'Core', route: AppRoutes.onboardingStep5),
  RouteRow(id: 'r48', title: 'heuristic Engine', dayRef: 'Day 44', section: 'Foundation', route: AppRoutes.heuristicEngine),
  RouteRow(id: 'r49', title: 'model Bundle', dayRef: 'Day 45', section: 'Foundation', route: AppRoutes.modelBundle),
  RouteRow(id: 'r50', title: 'detection Settings', dayRef: 'Day 46', section: 'Foundation', route: AppRoutes.detectionSettings),
  RouteRow(id: 'r51', title: 'integration Tests', dayRef: 'Day 47', section: 'Foundation', route: AppRoutes.integrationTests),
  RouteRow(id: 'r52', title: 'device Diagnostics', dayRef: 'Day 48', section: 'Foundation', route: AppRoutes.deviceDiagnostics),
  RouteRow(id: 'r53', title: 'audio Pipeline', dayRef: 'Day 49', section: 'Foundation', route: AppRoutes.audioPipeline),
  RouteRow(id: 'r54', title: 'motion Validation', dayRef: 'Day 50', section: 'Foundation', route: AppRoutes.motionValidation),
  RouteRow(id: 'r55', title: 'offline Status', dayRef: 'Day 51', section: 'Foundation', route: AppRoutes.offlineStatus),
  RouteRow(id: 'r56', title: 'phone Capability', dayRef: 'Day 52', section: 'Foundation', route: AppRoutes.phoneCapability),
  RouteRow(id: 'r57', title: 'compatibility Matrix', dayRef: 'Day 53', section: 'Foundation', route: AppRoutes.compatibilityMatrix),
  RouteRow(id: 'r58', title: 'capability Report', dayRef: 'Day 54', section: 'Foundation', route: AppRoutes.capabilityReport),
  RouteRow(id: 'r59', title: 'detection Events', dayRef: 'Day 55', section: 'Foundation', route: AppRoutes.detectionEvents),
  RouteRow(id: 'r60', title: 'model Downloads', dayRef: 'Day 56', section: 'Foundation', route: AppRoutes.modelDownloads),
  RouteRow(id: 'r61', title: 'ml Analytics', dayRef: 'Day 57', section: 'Foundation', route: AppRoutes.mlAnalytics),
  RouteRow(id: 'r62', title: 'safe Zones', dayRef: 'Day 58', section: 'Foundation', route: AppRoutes.safeZones),
  RouteRow(id: 'r63', title: 'protection Score', dayRef: 'Day 59', section: 'Foundation', route: AppRoutes.protectionScore),
  RouteRow(id: 'r64', title: 'drill Mode', dayRef: 'Day 60', section: 'Foundation', route: AppRoutes.drillMode),
  RouteRow(id: 'r65', title: 'inference Log', dayRef: 'Day 61', section: 'Foundation', route: AppRoutes.inferenceLog),
  RouteRow(id: 'r66', title: 'incident Report', dayRef: 'Day 62', section: 'Foundation', route: AppRoutes.incidentReport),
  RouteRow(id: 'r67', title: 'alert Thresholds', dayRef: 'Day 63', section: 'Foundation', route: AppRoutes.alertThresholds),
  RouteRow(id: 'r68', title: 'escalation Policies', dayRef: 'Day 64', section: 'Foundation', route: AppRoutes.escalationPolicies),
  RouteRow(id: 'r69', title: 'check Ins', dayRef: 'Day 65', section: 'Foundation', route: AppRoutes.checkIns),
  RouteRow(id: 'r70', title: 'sos Templates', dayRef: 'Day 66', section: 'Foundation', route: AppRoutes.sosTemplates),
  RouteRow(id: 'r71', title: 'notification Prefs', dayRef: 'Day 67', section: 'Foundation', route: AppRoutes.notificationPrefs),
  RouteRow(id: 'r72', title: 'audit Log', dayRef: 'Day 68', section: 'Foundation', route: AppRoutes.auditLog),
  RouteRow(id: 'r73', title: 'data Export', dayRef: 'Day 69', section: 'Foundation', route: AppRoutes.dataExport),
  RouteRow(id: 'r74', title: 'privacy', dayRef: 'Day 70', section: 'Foundation', route: AppRoutes.privacy),
  RouteRow(id: 'r75', title: 'alert Pending', dayRef: 'Day 71', section: 'SOS', route: AppRoutes.alertPending),
  RouteRow(id: 'r76', title: 'do Not Disturb', dayRef: 'Day 73', section: 'SOS', route: AppRoutes.doNotDisturb),
  RouteRow(id: 'r77', title: 'delivery Confirmation', dayRef: 'Day 75', section: 'SOS', route: AppRoutes.deliveryConfirmation),
  RouteRow(id: 'r78', title: 'notification History', dayRef: 'Day 76', section: 'SOS', route: AppRoutes.notificationHistory),
  RouteRow(id: 'r79', title: 'alert Dashboard', dayRef: 'Day 77-78', section: 'SOS', route: AppRoutes.alertDashboard),
  RouteRow(id: 'r80', title: 'alert Dashboard V2', dayRef: 'Day 80', section: 'SOS', route: AppRoutes.alertDashboardV2),
  RouteRow(id: 'r81', title: 'settings V2', dayRef: 'Day 81', section: 'SOS', route: AppRoutes.settingsV2),
  RouteRow(id: 'r82', title: 'evidence Vault', dayRef: 'Day 82', section: 'SOS', route: AppRoutes.evidenceVault),
  RouteRow(id: 'r83', title: 'contacts V2', dayRef: 'Day 83', section: 'SOS', route: AppRoutes.contactsV2),
  RouteRow(id: 'r84', title: 'emergency Drills', dayRef: 'Day 84', section: 'SOS', route: AppRoutes.emergencyDrills),
  RouteRow(id: 'r85', title: 'alert Thresholds V2', dayRef: 'Day 85', section: 'SOS', route: AppRoutes.alertThresholdsV2),
  RouteRow(id: 'r86', title: 'escalation Policies V2', dayRef: 'Day 86', section: 'SOS', route: AppRoutes.escalationPoliciesV2),
  RouteRow(id: 'r87', title: 'sos Templates V2', dayRef: 'Day 87', section: 'SOS', route: AppRoutes.sosTemplatesV2),
  RouteRow(id: 'r88', title: 'notification History V2', dayRef: 'Day 88', section: 'SOS', route: AppRoutes.notificationHistoryV2),
  RouteRow(id: 'r89', title: 'activity Audit Log V2', dayRef: 'Day 89', section: 'SOS', route: AppRoutes.activityAuditLogV2),
  RouteRow(id: 'r90', title: 'data Privacy V2', dayRef: 'Day 90', section: 'SOS', route: AppRoutes.dataPrivacyV2),
  RouteRow(id: 'r91', title: 'premium Subscription', dayRef: 'Day 91-92', section: 'SOS', route: AppRoutes.premiumSubscription),
  RouteRow(id: 'r92', title: 'premium Features', dayRef: 'Day 92-93', section: 'SOS', route: AppRoutes.premiumFeatures),
  RouteRow(id: 'r93', title: 'subscription Mgmt', dayRef: 'Day 93-94', section: 'SOS', route: AppRoutes.subscriptionMgmt),
  RouteRow(id: 'r94', title: 'payment Methods', dayRef: 'Day 94-95', section: 'SOS', route: AppRoutes.paymentMethods),
  RouteRow(id: 'r95', title: 'billing History', dayRef: 'Day 95-96', section: 'SOS', route: AppRoutes.billingHistory),
  RouteRow(id: 'r96', title: 'language Settings', dayRef: 'Day 96-97', section: 'SOS', route: AppRoutes.languageSettings),
  RouteRow(id: 'r97', title: 'accessibility Settings', dayRef: 'Day 97', section: 'SOS', route: AppRoutes.accessibilitySettings),
  RouteRow(id: 'r98', title: 'profile Account', dayRef: 'Day 98', section: 'SOS', route: AppRoutes.profileAccount),
  RouteRow(id: 'r99', title: 'help Support', dayRef: 'Day 99', section: 'SOS', route: AppRoutes.helpSupport),
  RouteRow(id: 'r100', title: 'milestone', dayRef: 'Day 100', section: 'SOS', route: AppRoutes.milestone),
  RouteRow(id: 'r101', title: 'i18n Setup', dayRef: 'Day 101', section: 'i18n', route: AppRoutes.i18nSetup),
  RouteRow(id: 'r102', title: 'translation Demo', dayRef: 'Day 102', section: 'i18n', route: AppRoutes.translationDemo),
  RouteRow(id: 'r103', title: 'translation Coverage', dayRef: 'Day 103', section: 'i18n', route: AppRoutes.translationCoverage),
  RouteRow(id: 'r104', title: 'onboarding I18n', dayRef: 'Day 104', section: 'i18n', route: AppRoutes.onboardingI18n),
  RouteRow(id: 'r105', title: 'month3 I18n', dayRef: 'Day 105', section: 'i18n', route: AppRoutes.month3I18n),
  RouteRow(id: 'r106', title: 'detection Flow', dayRef: 'Day 106', section: 'i18n', route: AppRoutes.detectionFlow),
  RouteRow(id: 'r107', title: 'month4 I18n', dayRef: 'Day 107', section: 'i18n', route: AppRoutes.month4I18n),
  RouteRow(id: 'r108', title: 'language Toggle', dayRef: 'Day 108', section: 'i18n', route: AppRoutes.languageToggle),
  RouteRow(id: 'r109', title: 'semantics A11y', dayRef: 'Day 109', section: 'i18n', route: AppRoutes.semanticsA11y),
  RouteRow(id: 'r110', title: 'a11y Contrast', dayRef: 'Day 110', section: 'i18n', route: AppRoutes.a11yContrast),
  RouteRow(id: 'r111', title: 'beta Flavor', dayRef: 'Day 111', section: 'i18n', route: AppRoutes.betaFlavor),
  RouteRow(id: 'r112', title: 'beta Onboarding', dayRef: 'Day 112', section: 'i18n', route: AppRoutes.betaOnboarding),
  RouteRow(id: 'r113', title: 'feedback Fab', dayRef: 'Day 113', section: 'i18n', route: AppRoutes.feedbackFab),
  RouteRow(id: 'r114', title: 'feedback Form', dayRef: 'Day 114', section: 'i18n', route: AppRoutes.feedbackForm),
  RouteRow(id: 'r115', title: 'false Positive', dayRef: 'Day 115', section: 'i18n', route: AppRoutes.falsePositive),
  RouteRow(id: 'r116', title: 'sentry Setup', dayRef: 'Day 116', section: 'i18n', route: AppRoutes.sentrySetup),
  RouteRow(id: 'r117', title: 'test Flight', dayRef: 'Day 117', section: 'i18n', route: AppRoutes.testFlight),
  RouteRow(id: 'r118', title: 'android Dist', dayRef: 'Day 118', section: 'i18n', route: AppRoutes.androidDist),
  RouteRow(id: 'r119', title: 'release Notes', dayRef: 'Day 119', section: 'i18n', route: AppRoutes.releaseNotes),
  RouteRow(id: 'r120', title: 'beta Launch', dayRef: 'Day 120', section: 'i18n', route: AppRoutes.betaLaunch),
  RouteRow(id: 'r121', title: 'feedback Analysis', dayRef: 'Day 121', section: 'Beta', route: AppRoutes.feedbackAnalysis),
  RouteRow(id: 'r122', title: 'crash Fixes', dayRef: 'Day 122-123', section: 'Beta', route: AppRoutes.crashFixes),
  RouteRow(id: 'r123', title: 'hotfix Release', dayRef: 'Day 123', section: 'Beta', route: AppRoutes.hotfixRelease),
  RouteRow(id: 'r124', title: 'false Positive Fix', dayRef: 'Day 124', section: 'Beta', route: AppRoutes.falsePositiveFix),
  RouteRow(id: 'r125', title: 'fp Verify', dayRef: 'Day 125', section: 'Beta', route: AppRoutes.fpVerify),
  RouteRow(id: 'r126', title: 'ui Bugs', dayRef: 'Day 126', section: 'Beta', route: AppRoutes.uiBugs),
  RouteRow(id: 'r127', title: 'notification Fixes', dayRef: 'Day 127', section: 'Beta', route: AppRoutes.notificationFixes),
  RouteRow(id: 'r128', title: 'contact Delivery', dayRef: 'Day 128', section: 'Beta', route: AppRoutes.contactDelivery),
  RouteRow(id: 'r129', title: 'performance', dayRef: 'Day 129', section: 'Beta', route: AppRoutes.performance),
  RouteRow(id: 'r130', title: 'memory Opt', dayRef: 'Day 130', section: 'Beta', route: AppRoutes.memoryOpt),
  RouteRow(id: 'r131', title: 'memory Leaks', dayRef: 'Day 131', section: 'Beta', route: AppRoutes.memoryLeaks),
  RouteRow(id: 'r132', title: 'leak Verify', dayRef: 'Day 132', section: 'Beta', route: AppRoutes.leakVerify),
  RouteRow(id: 'r133', title: 'onboarding Simplify', dayRef: 'Day 133', section: 'Beta', route: AppRoutes.onboardingSimplify),
  RouteRow(id: 'r134', title: 'onboarding Polish', dayRef: 'Day 134', section: 'Beta', route: AppRoutes.onboardingPolish),
  RouteRow(id: 'r135', title: 'release Bundle', dayRef: 'Day 135', section: 'Beta', route: AppRoutes.releaseBundle),
  RouteRow(id: 'r136', title: 'feedback Round2', dayRef: 'Day 136', section: 'Beta', route: AppRoutes.feedbackRound2),
  RouteRow(id: 'r137', title: 'iteration Decision', dayRef: 'Day 137', section: 'Beta', route: AppRoutes.iterationDecision),
  RouteRow(id: 'r138', title: 'final Polish', dayRef: 'Day 138', section: 'Beta', route: AppRoutes.finalPolish),
  RouteRow(id: 'r139', title: 'security Review', dayRef: 'Day 139', section: 'Beta', route: AppRoutes.securityReview),
  RouteRow(id: 'r140', title: 'beta Final', dayRef: 'Day 140', section: 'Beta', route: AppRoutes.betaFinal),
  RouteRow(id: 'r141', title: 'app Size Audit', dayRef: 'Day 141', section: 'Release', route: AppRoutes.appSizeAudit),
  RouteRow(id: 'r142', title: 'model Compress', dayRef: 'Day 142', section: 'Release', route: AppRoutes.modelCompress),
  RouteRow(id: 'r143', title: 'lazy Load', dayRef: 'Day 143', section: 'Release', route: AppRoutes.lazyLoad),
  RouteRow(id: 'r144', title: 'asset Optimise', dayRef: 'Day 144', section: 'Release', route: AppRoutes.assetOptimise),
  RouteRow(id: 'r145', title: 'cold Start', dayRef: 'Day 145', section: 'Release', route: AppRoutes.coldStart),
  RouteRow(id: 'r146', title: 'aws Url', dayRef: 'Day 146', section: 'Release', route: AppRoutes.awsUrl),
  RouteRow(id: 'r147', title: 'aws Test', dayRef: 'Day 147', section: 'Release', route: AppRoutes.awsTest),
  RouteRow(id: 'r148', title: 'aws Issues', dayRef: 'Day 148', section: 'Release', route: AppRoutes.awsIssues),
  RouteRow(id: 'r149', title: 'regression Test', dayRef: 'Day 149', section: 'Release', route: AppRoutes.regressionTest),
  RouteRow(id: 'r150', title: 'production Release', dayRef: 'Day 150', section: 'Release', route: AppRoutes.productionRelease),
  RouteRow(id: 'r151', title: 'privacy Policy', dayRef: 'Day 151-152', section: 'Legal', route: AppRoutes.privacyPolicy),
  RouteRow(id: 'r152', title: 'policy Consent', dayRef: 'Day 152', section: 'Legal', route: AppRoutes.policyConsent),
  RouteRow(id: 'r153', title: 'terms Of Service', dayRef: 'Day 153-154', section: 'Legal', route: AppRoutes.termsOfService),
  RouteRow(id: 'r154', title: 'legal Hub', dayRef: 'Day 154', section: 'Legal', route: AppRoutes.legalHub),
  RouteRow(id: 'r155', title: 'consent Management', dayRef: 'Day 155-157', section: 'Legal', route: AppRoutes.consentManagement),
  RouteRow(id: 'r156', title: 'consent Gates', dayRef: 'Day 156', section: 'Legal', route: AppRoutes.consentGates),
  RouteRow(id: 'r157', title: 'privacy Settings', dayRef: 'Day 157', section: 'Legal', route: AppRoutes.privacySettings),
  RouteRow(id: 'r158', title: 'app Permissions', dayRef: 'Day 158-160', section: 'Legal', route: AppRoutes.appPermissions),
  RouteRow(id: 'r159', title: 'permission Flow', dayRef: 'Day 159', section: 'Legal', route: AppRoutes.permissionFlow),
  RouteRow(id: 'r160', title: 'permission Recovery', dayRef: 'Day 160', section: 'Legal', route: AppRoutes.permissionRecovery),
  RouteRow(id: 'r161', title: 'consent Gate', dayRef: 'Day 161-162', section: 'Legal', route: AppRoutes.consentGate),
  RouteRow(id: 'r162', title: 'consent Flow Tests', dayRef: 'Day 162', section: 'Legal', route: AppRoutes.consentFlowTests),
  RouteRow(id: 'r163', title: 'analytics Prefs', dayRef: 'Day 163-165', section: 'Legal', route: AppRoutes.analyticsPrefs),
  RouteRow(id: 'r164', title: 'data Safety', dayRef: 'Day 164', section: 'Legal', route: AppRoutes.dataSafety),
  RouteRow(id: 'r165', title: 'analytics Hub', dayRef: 'Day 165', section: 'Legal', route: AppRoutes.analyticsHub),
  RouteRow(id: 'r166', title: 'data Export Request', dayRef: 'Day 166', section: 'GDPR', route: AppRoutes.dataExportRequest),
  RouteRow(id: 'r167', title: 'data Export Download', dayRef: 'Day 167', section: 'GDPR', route: AppRoutes.dataExportDownload),
  RouteRow(id: 'r168', title: 'data Export Edge Cases', dayRef: 'Day 168', section: 'GDPR', route: AppRoutes.dataExportEdgeCases),
  RouteRow(id: 'r169', title: 'account Deletion Request', dayRef: 'Day 169', section: 'GDPR', route: AppRoutes.accountDeletionRequest),
  RouteRow(id: 'r170', title: 'account Deletion Grace', dayRef: 'Day 170', section: 'GDPR', route: AppRoutes.accountDeletionGrace),
  RouteRow(id: 'r171', title: 'account Deletion Final', dayRef: 'Day 171', section: 'GDPR', route: AppRoutes.accountDeletionFinal),
  RouteRow(id: 'r172', title: 'account Deletion Edge Cases', dayRef: 'Day 172', section: 'GDPR', route: AppRoutes.accountDeletionEdgeCases),
  RouteRow(id: 'r173', title: 'data Access Audit', dayRef: 'Day 173', section: 'GDPR', route: AppRoutes.dataAccessAudit),
  RouteRow(id: 'r174', title: 'data Access Audit Detail', dayRef: 'Day 174', section: 'GDPR', route: AppRoutes.dataAccessAuditDetail),
  RouteRow(id: 'r175', title: 'third Party Access', dayRef: 'Day 175', section: 'GDPR', route: AppRoutes.thirdPartyAccess),
  RouteRow(id: 'r176', title: 'data Retention Settings', dayRef: 'Day 176', section: 'GDPR', route: AppRoutes.dataRetentionSettings),
  RouteRow(id: 'r177', title: 'data Retention Scheduler', dayRef: 'Day 177', section: 'GDPR', route: AppRoutes.dataRetentionScheduler),
  RouteRow(id: 'r178', title: 'data Retention Edge Cases', dayRef: 'Day 178', section: 'GDPR', route: AppRoutes.dataRetentionEdgeCases),
  RouteRow(id: 'r179', title: 'active Sessions', dayRef: 'Day 179', section: 'GDPR', route: AppRoutes.activeSessions),
  RouteRow(id: 'r180', title: 'session Security', dayRef: 'Day 180', section: 'GDPR', route: AppRoutes.sessionSecurity),
  RouteRow(id: 'r181', title: 'cert Pinning', dayRef: 'Day 181', section: 'Security', route: AppRoutes.certPinning),
  RouteRow(id: 'r182', title: 'network Security', dayRef: 'Day 182', section: 'Security', route: AppRoutes.networkSecurity),
  RouteRow(id: 'r183', title: 'biometric Lock', dayRef: 'Day 183', section: 'Security', route: AppRoutes.biometricLock),
  RouteRow(id: 'r184', title: 'biometric Hardening', dayRef: 'Day 184', section: 'Security', route: AppRoutes.biometricHardening),
  RouteRow(id: 'r185', title: 'root Detection', dayRef: 'Day 185', section: 'Security', route: AppRoutes.rootDetection),
  RouteRow(id: 'r186', title: 'tamper Alert', dayRef: 'Day 186', section: 'Security', route: AppRoutes.tamperAlert),
  RouteRow(id: 'r187', title: 'secure Storage', dayRef: 'Day 187', section: 'Security', route: AppRoutes.secureStorage),
  RouteRow(id: 'r188', title: 'key Rotation', dayRef: 'Day 188', section: 'Security', route: AppRoutes.keyRotation),
  RouteRow(id: 'r189', title: 'security Dashboard', dayRef: 'Day 189', section: 'Security', route: AppRoutes.securityDashboard),
  RouteRow(id: 'r190', title: 'section C Complete', dayRef: 'Day 190', section: 'Security', route: AppRoutes.sectionCComplete),
  RouteRow(id: 'r191', title: 'screenshots', dayRef: 'Day 191', section: 'Security', route: AppRoutes.screenshots),
  RouteRow(id: 'r192', title: 'screenshot Frames', dayRef: 'Day 192', section: 'Security', route: AppRoutes.screenshotFrames),
  RouteRow(id: 'r193', title: 'store Listing', dayRef: 'Day 193', section: 'Security', route: AppRoutes.storeListing),
  RouteRow(id: 'r194', title: 'store Listing Extra', dayRef: 'Day 194', section: 'Security', route: AppRoutes.storeListingExtra),
  RouteRow(id: 'r195', title: 'privacy Compliance', dayRef: 'Day 195', section: 'Security', route: AppRoutes.privacyCompliance),
  RouteRow(id: 'r196', title: 'privacy Alignment', dayRef: 'Day 196', section: 'Security', route: AppRoutes.privacyAlignment),
  RouteRow(id: 'r197', title: 'release Checklist', dayRef: 'Day 197', section: 'Security', route: AppRoutes.releaseChecklist),
  RouteRow(id: 'r198', title: 'qa Pass', dayRef: 'Day 198', section: 'Security', route: AppRoutes.qaPass),
  RouteRow(id: 'r199', title: 'final Submission', dayRef: 'Day 199', section: 'Security', route: AppRoutes.finalSubmission),
  RouteRow(id: 'r200', title: 'grand Finale', dayRef: 'Day 200', section: 'Security', route: AppRoutes.grandFinale),
  RouteRow(id: 'r201', title: 'device Qa Harness', dayRef: 'Day 201', section: 'Polish', route: AppRoutes.deviceQaHarness),
  RouteRow(id: 'r202', title: 'dashboard Notifications', dayRef: 'Day 202', section: 'Polish', route: AppRoutes.dashboardNotifications),
  RouteRow(id: 'r203', title: 'sos Long Press Ring', dayRef: 'Day 203', section: 'Polish', route: AppRoutes.sosLongPressRing),
  RouteRow(id: 'r204', title: 'mode Status Card', dayRef: 'Day 204', section: 'Polish', route: AppRoutes.modeStatusCard),
  RouteRow(id: 'r205', title: 'onboarding Skip Paths', dayRef: 'Day 205', section: 'Polish', route: AppRoutes.onboardingSkipPaths),
  RouteRow(id: 'r206', title: 'vault Search Filter', dayRef: 'Day 206', section: 'Polish', route: AppRoutes.vaultSearchFilter),
  RouteRow(id: 'r207', title: 'chat Offline Queue', dayRef: 'Day 207', section: 'Polish', route: AppRoutes.chatOfflineQueue),
  RouteRow(id: 'r208', title: 'design System Audit', dayRef: 'Day 208', section: 'Polish', route: AppRoutes.designSystemAudit),
  RouteRow(id: 'r209', title: 'loading States', dayRef: 'Day 209', section: 'Polish', route: AppRoutes.loadingStates),
  RouteRow(id: 'r210', title: 'error States', dayRef: 'Day 210', section: 'Polish', route: AppRoutes.errorStates),
  RouteRow(id: 'r211', title: 'dark Mode Audit', dayRef: 'Day 211', section: 'Polish', route: AppRoutes.darkModeAudit),
  RouteRow(id: 'r212', title: 'empty States', dayRef: 'Day 212', section: 'Polish', route: AppRoutes.emptyStates),
  RouteRow(id: 'r213', title: 'animation Polish', dayRef: 'Day 213', section: 'Polish', route: AppRoutes.animationPolish),
  RouteRow(id: 'r214', title: 'a11y Screen Reader Audit', dayRef: 'Day 214', section: 'Polish', route: AppRoutes.a11yScreenReaderAudit),
  RouteRow(id: 'r215', title: 'font Scale Regression', dayRef: 'Day 215', section: 'Polish', route: AppRoutes.fontScaleRegression),
  RouteRow(id: 'r216', title: 'i18n Coverage Audit', dayRef: 'Day 216', section: 'Polish', route: AppRoutes.i18nCoverageAudit),
  RouteRow(id: 'r217', title: 'performance Profiling', dayRef: 'Day 217', section: 'Polish', route: AppRoutes.performanceProfiling),
  RouteRow(id: 'r218', title: 'tflite Integration Checklist', dayRef: 'Day 218', section: 'Polish', route: AppRoutes.tfliteIntegrationChecklist),
  RouteRow(id: 'r219', title: 'backend Integration Audit', dayRef: 'Day 219', section: 'Polish', route: AppRoutes.backendIntegrationAudit),
  RouteRow(id: 'r220', title: 'polish Milestone', dayRef: 'Day 220', section: 'Polish', route: AppRoutes.polishMilestone),
  RouteRow(id: 'r221', title: 'police Dashboard', dayRef: 'Day 221', section: 'Section B', route: AppRoutes.policeDashboard),
  RouteRow(id: 'r222', title: 'police Dispatch Status', dayRef: 'Day 222', section: 'Section B', route: AppRoutes.policeDispatchStatus),
  RouteRow(id: 'r223', title: 'police Weblink Preview', dayRef: 'Day 223', section: 'Section B', route: AppRoutes.policeWeblinkPreview),
  RouteRow(id: 'r224', title: 'referral Invite', dayRef: 'Day 224', section: 'Section B', route: AppRoutes.referralInvite),
  RouteRow(id: 'r225', title: 'referral Rewards', dayRef: 'Day 225', section: 'Section B', route: AppRoutes.referralRewards),
  RouteRow(id: 'r226', title: 'admin Analytics', dayRef: 'Day 226', section: 'Section B', route: AppRoutes.adminAnalytics),
  RouteRow(id: 'r227', title: 'notification History V3', dayRef: 'Day 227', section: 'Section B', route: AppRoutes.notificationHistoryV3),
  RouteRow(id: 'r228', title: 'sos History Timeline', dayRef: 'Day 228', section: 'Section B', route: AppRoutes.sosHistoryTimeline),
  RouteRow(id: 'r229', title: 'feature Regression Runner', dayRef: 'Day 229', section: 'Section B', route: AppRoutes.featureRegressionRunner),
  RouteRow(id: 'r230', title: 'hidden Mode Toggle', dayRef: 'Day 230', section: 'Section B', route: AppRoutes.hiddenModeToggle),
  RouteRow(id: 'r231', title: 'stealth Icon Disguise', dayRef: 'Day 231', section: 'Section B', route: AppRoutes.stealthIconDisguise),
  RouteRow(id: 'r232', title: 'decoy Calculator', dayRef: 'Day 232', section: 'Section B', route: AppRoutes.decoyCalculator),
  RouteRow(id: 'r233', title: 'decoy Weather', dayRef: 'Day 233', section: 'Section B', route: AppRoutes.decoyWeather),
  RouteRow(id: 'r234', title: 'secret Gesture Config', dayRef: 'Day 234', section: 'Section B', route: AppRoutes.secretGestureConfig),
  RouteRow(id: 'r235', title: 'stealth Settings Hub', dayRef: 'Day 235', section: 'Section B', route: AppRoutes.stealthSettingsHub),
  RouteRow(id: 'r236', title: 'hindi Ux Qa', dayRef: 'Day 236', section: 'Section B', route: AppRoutes.hindiUxQa),
  RouteRow(id: 'r237', title: 'tamil Telugu Qa', dayRef: 'Day 237', section: 'Section B', route: AppRoutes.tamilTeluguQa),
  RouteRow(id: 'r238', title: 'region Emergency Numbers', dayRef: 'Day 238', section: 'Section B', route: AppRoutes.regionEmergencyNumbers),
  RouteRow(id: 'r239', title: 'india Launch Readiness', dayRef: 'Day 239', section: 'Section B', route: AppRoutes.indiaLaunchReadiness),
  RouteRow(id: 'r240', title: 'section B Catchup Milestone', dayRef: 'Day 240', section: 'Section B', route: AppRoutes.sectionBCatchupMilestone),
  RouteRow(id: 'r241', title: 'journey Mode V2', dayRef: 'Day 241', section: 'Section C', route: AppRoutes.journeyModeV2),
  RouteRow(id: 'r242', title: 'trusted Circle V2', dayRef: 'Day 242', section: 'Section C', route: AppRoutes.trustedCircleV2),
  RouteRow(id: 'r243', title: 'ride Safety V2', dayRef: 'Day 243', section: 'Section C', route: AppRoutes.rideSafetyV2),
  RouteRow(id: 'r244', title: 'fake Call Polish', dayRef: 'Day 244', section: 'Section C', route: AppRoutes.fakeCallPolish),
  RouteRow(id: 'r245', title: 'offline Sos Ux', dayRef: 'Day 245', section: 'Section C', route: AppRoutes.offlineSosUx),
  RouteRow(id: 'r246', title: 'hearing Impaired Visual', dayRef: 'Day 246', section: 'Section C', route: AppRoutes.hearingImpairedVisual),
  RouteRow(id: 'r247', title: 'haptic Patterns', dayRef: 'Day 247', section: 'Section C', route: AppRoutes.hapticPatterns),
  RouteRow(id: 'r248', title: 'siri Shortcuts', dayRef: 'Day 248', section: 'Section C', route: AppRoutes.siriShortcuts),
  RouteRow(id: 'r249', title: 'voice Assistant Setup', dayRef: 'Day 249', section: 'Section C', route: AppRoutes.voiceAssistantSetup),
  RouteRow(id: 'r250', title: 'group Journey Create', dayRef: 'Day 250', section: 'Section C', route: AppRoutes.groupJourneyCreate),
  RouteRow(id: 'r251', title: 'group Journey Live Map', dayRef: 'Day 251', section: 'Section C', route: AppRoutes.groupJourneyLiveMap),
  RouteRow(id: 'r252', title: 'group Journey Panic', dayRef: 'Day 252', section: 'Section C', route: AppRoutes.groupJourneyPanic),
  RouteRow(id: 'r253', title: 'family Alerts Dashboard', dayRef: 'Day 253', section: 'Section C', route: AppRoutes.familyAlertsDashboard),
  RouteRow(id: 'r254', title: 'family Sos History', dayRef: 'Day 254', section: 'Section C', route: AppRoutes.familySosHistory),
  RouteRow(id: 'r255', title: 'child Mode Admin', dayRef: 'Day 255', section: 'Section C', route: AppRoutes.childModeAdmin),
  RouteRow(id: 'r256', title: 'home Widget Sos', dayRef: 'Day 256', section: 'Section C', route: AppRoutes.homeWidgetSos),
  RouteRow(id: 'r257', title: 'home Widget Score', dayRef: 'Day 257', section: 'Section C', route: AppRoutes.homeWidgetScore),
  RouteRow(id: 'r258', title: 'fall Detection Tuning', dayRef: 'Day 258', section: 'Section C', route: AppRoutes.fallDetectionTuning),
  RouteRow(id: 'r259', title: 'smart Notifications', dayRef: 'Day 259', section: 'Section C', route: AppRoutes.smartNotifications),
  RouteRow(id: 'r260', title: 'section C Advanced Milestone', dayRef: 'Day 260', section: 'Section C', route: AppRoutes.sectionCAdvancedMilestone),
  RouteRow(id: 'r261', title: 'language Expansion Hub', dayRef: 'Day 261', section: 'Section D', route: AppRoutes.languageExpansionHub),
  RouteRow(id: 'r262', title: 'translation Workflow', dayRef: 'Day 262', section: 'Section D', route: AppRoutes.translationWorkflow),
  RouteRow(id: 'r263', title: 'persian Rtl', dayRef: 'Day 263', section: 'Section D', route: AppRoutes.persianRtl),
  RouteRow(id: 'r264', title: 'indonesian Pack', dayRef: 'Day 264', section: 'Section D', route: AppRoutes.indonesianPack),
  RouteRow(id: 'r265', title: 'vietnamese Pack', dayRef: 'Day 265', section: 'Section D', route: AppRoutes.vietnamesePack),
  RouteRow(id: 'r266', title: 'japanese Pack', dayRef: 'Day 266', section: 'Section D', route: AppRoutes.japanesePack),
  RouteRow(id: 'r267', title: 'korean Pack', dayRef: 'Day 267', section: 'Section D', route: AppRoutes.koreanPack),
  RouteRow(id: 'r268', title: 'multilang Qa Runner', dayRef: 'Day 268', section: 'Section D', route: AppRoutes.multilangQaRunner),
  RouteRow(id: 'r269', title: 'cultural Adaptation', dayRef: 'Day 269', section: 'Section D', route: AppRoutes.culturalAdaptation),
  RouteRow(id: 'r270', title: 'community Heatmap', dayRef: 'Day 270', section: 'Section D', route: AppRoutes.communityHeatmap),
  RouteRow(id: 'r271', title: 'share Safe Route', dayRef: 'Day 271', section: 'Section D', route: AppRoutes.shareSafeRoute),
  RouteRow(id: 'r272', title: 'insurance Partnership', dayRef: 'Day 272', section: 'Section D', route: AppRoutes.insurancePartnership),
  RouteRow(id: 'r273', title: 'personal Analytics Hub', dayRef: 'Day 273', section: 'Section D', route: AppRoutes.personalAnalyticsHub),
  RouteRow(id: 'r274', title: 'weekly Digest V2', dayRef: 'Day 274', section: 'Section D', route: AppRoutes.weeklyDigestV2),
  RouteRow(id: 'r275', title: 'year In Review', dayRef: 'Day 275', section: 'Section D', route: AppRoutes.yearInReview),
  RouteRow(id: 'r276', title: 'reverse Image Search', dayRef: 'Day 276', section: 'Section D', route: AppRoutes.reverseImageSearch),
  RouteRow(id: 'r277', title: 'enterprise B2b Preview', dayRef: 'Day 277', section: 'Section D', route: AppRoutes.enterpriseB2bPreview),
  RouteRow(id: 'r278', title: 'counselor Queue Polish', dayRef: 'Day 278', section: 'Section D', route: AppRoutes.counselorQueuePolish),
  RouteRow(id: 'r279', title: 'production Dashboard', dayRef: 'Day 279', section: 'Section D', route: AppRoutes.productionDashboard),
  RouteRow(id: 'r280', title: 'section D Milestone', dayRef: 'Day 280', section: 'Section D', route: AppRoutes.sectionDMilestone),
  RouteRow(id: 'r281', title: 'landing Preview', dayRef: 'Day 281', section: 'Section E', route: AppRoutes.landingPreview),
  RouteRow(id: 'r282', title: 'press Kit', dayRef: 'Day 282', section: 'Section E', route: AppRoutes.pressKit),
  RouteRow(id: 'r283', title: 'demo Video Storyboard', dayRef: 'Day 283', section: 'Section E', route: AppRoutes.demoVideoStoryboard),
  RouteRow(id: 'r284', title: 'store Review Notes', dayRef: 'Day 284', section: 'Section E', route: AppRoutes.storeReviewNotes),
  RouteRow(id: 'r285', title: 'security Prelaunch Audit', dayRef: 'Day 285', section: 'Section E', route: AppRoutes.securityPrelaunchAudit),
  RouteRow(id: 'r286', title: 'legal Blockers Tracker', dayRef: 'Day 286', section: 'Section E', route: AppRoutes.legalBlockersTracker),
  RouteRow(id: 'r287', title: 'beta Feedback Round3', dayRef: 'Day 287', section: 'Section E', route: AppRoutes.betaFeedbackRound3),
  RouteRow(id: 'r288', title: 'crash Free Tracker', dayRef: 'Day 288', section: 'Section E', route: AppRoutes.crashFreeTracker),
  RouteRow(id: 'r289', title: 'full Regression Runner', dayRef: 'Day 289', section: 'Section E', route: AppRoutes.fullRegressionRunner),
  RouteRow(id: 'r290', title: 'staged Rollout Simulator', dayRef: 'Day 290', section: 'Section E', route: AppRoutes.stagedRolloutSimulator),
  RouteRow(id: 'r291', title: 'global India Compare', dayRef: 'Day 291', section: 'Section E', route: AppRoutes.globalIndiaCompare),
  RouteRow(id: 'r292', title: 'post Launch Monitoring', dayRef: 'Day 292', section: 'Section E', route: AppRoutes.postLaunchMonitoring),
  RouteRow(id: 'r293', title: 'hotfix Playbook', dayRef: 'Day 293', section: 'Section E', route: AppRoutes.hotfixPlaybook),
  RouteRow(id: 'r294', title: 'support Macros', dayRef: 'Day 294', section: 'Section E', route: AppRoutes.supportMacros),
  RouteRow(id: 'r295', title: 'phase2 Roadmap', dayRef: 'Day 295', section: 'Section E', route: AppRoutes.phase2Roadmap),
  RouteRow(id: 'r296', title: 'platform Parity Audit', dayRef: 'Day 296', section: 'Section E', route: AppRoutes.platformParityAudit),
  RouteRow(id: 'r297', title: 'battery Soak Log', dayRef: 'Day 297', section: 'Section E', route: AppRoutes.batterySoakLog),
  RouteRow(id: 'r298', title: 'gonogo Gate', dayRef: 'Day 298', section: 'Section E', route: AppRoutes.gonogoGate),
  RouteRow(id: 'r299', title: 'penultimate Summary', dayRef: 'Day 299', section: 'Section E', route: AppRoutes.penultimateSummary),
  RouteRow(id: 'r300', title: 'day300 Milestone', dayRef: 'Day 300', section: 'Section E', route: AppRoutes.day300Milestone),

  // ── Day 332 extension: Section F (Days 301-310) + Day 331 ──────────────
  // Added for Day 332's v2 runner, which extends this same catalogue per
  // spec rather than duplicating it. Days 311-330 (Section G/H) are not
  // present in this worktree as of this commit — built on a parallel
  // branch — so they cannot be added here honestly; Day 332's own header
  // documents this gap explicitly.
  RouteRow(id: 'r301', title: 'integration Audit', dayRef: 'Day 301', section: 'Section F', route: AppRoutes.integrationAudit),
  RouteRow(id: 'r302', title: 'analytics Live Wire', dayRef: 'Day 302', section: 'Section F', route: AppRoutes.analyticsLiveWire),
  RouteRow(id: 'r303', title: 'razorpay Live Wire', dayRef: 'Day 303', section: 'Section F', route: AppRoutes.razorpayLiveWire),
  RouteRow(id: 'r304', title: 'delivery Status Live Wire', dayRef: 'Day 304', section: 'Section F', route: AppRoutes.deliveryStatusLiveWire),
  RouteRow(id: 'r305', title: 'accept Language Wire', dayRef: 'Day 305', section: 'Section F', route: AppRoutes.acceptLanguageWire),
  RouteRow(id: 'r306', title: 'notification Tiers Polish', dayRef: 'Day 306', section: 'Section F', route: AppRoutes.notificationTiersPolish),
  RouteRow(id: 'r307', title: 'sos Longpress Ring Polish', dayRef: 'Day 307', section: 'Section F', route: AppRoutes.sosLongPressRingPolish),
  RouteRow(id: 'r308', title: 'status Card Polish', dayRef: 'Day 308', section: 'Section F', route: AppRoutes.statusCardPolish),
  RouteRow(id: 'r309', title: 'evidence Vault Search Polish', dayRef: 'Day 309', section: 'Section F', route: AppRoutes.evidenceVaultSearchPolish),
  RouteRow(id: 'r310', title: 'section F Milestone', dayRef: 'Day 310', section: 'Section F', route: AppRoutes.sectionFMilestone),
  RouteRow(id: 'r331', title: 'gonogo Gate V2', dayRef: 'Day 331', section: 'Section I', route: AppRoutes.gonogoGateV2),
];

const kRouteCount = 311;
