"""Day 391 (frontend) / Day 353 (ML) - golden fixture for the Dart wiring.

Generated by the SAME tokenizer and the SAME .tflite that the cross-corpus
run scored, so a mismatch in Dart is a Dart bug rather than a disagreement
about the spec. That is the rule every other golden file here follows.

WHAT THE CASES ARE CHOSEN TO CATCH
==================================
* `english_aggressive` / `english_calm`  - the basic signal
* `hindi_devanagari`   - the tokenizer's `[^\\x00-\\x7f]+` branch. A plain
                         `[a-z0-9']+` silently deletes ALL Hindi and returns
                         an all-pad vector that still scores confidently.
                         This case is the whole reason the branch exists.
* `hindi_romanised`    - Hindi written in Latin script, which is most of
                         TRAC's Hindi half; must tokenize like English
* `mixed_script`       - one string crossing the branch boundary
* `apostrophe`         - `'` is INSIDE the token class, so "don't" is one
                         token, not two
* `oov_only`           - every token unknown -> all index 1, not index 0.
                         Confusing OOV with pad is a classic silent bug.
* `empty`              - no tokens at all -> all pad
* `over_maxlen`        - 80 tokens truncated to 60, not wrapped or dropped
* `emoji`              - non-BMP characters. Python iterates code points and
                         Dart iterates UTF-16 code units, so this is where
                         the two could disagree about token boundaries.
* `uppercase`          - lowercasing happens before tokenizing
"""
from __future__ import annotations

import io
import json
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
TOKEN_RE = re.compile(r"[a-z0-9']+|[^\x00-\x7f]+")
MAXLEN = 60

CASES = {
    "english_aggressive": "you are a worthless idiot and I will find you",
    "english_calm": "thanks for the update, see you at the meeting tomorrow",
    "hindi_devanagari": "तुम बहुत बुरे हो मैं तुम्हें छोड़ूंगा नहीं",
    "hindi_romanised": "tum bahut bure ho main tumhe chodunga nahi",
    "mixed_script": "you are a गंदा आदमी and everyone knows it",
    "apostrophe": "don't you dare talk to me like that, i won't allow it",
    "oov_only": "zzqqxx flurble wumpus grobnitz",
    "empty": "",
    "over_maxlen": " ".join("word%d" % i for i in range(80)),
    "emoji": "you are trash 😡😡 get lost",
    "uppercase": "YOU ARE A WORTHLESS IDIOT AND I WILL FIND YOU",
}


def tokenize(t):
    return TOKEN_RE.findall((t or "").lower())


def encode(text, vocab):
    x = np.zeros(MAXLEN, np.int32)
    for j, w in enumerate(tokenize(text)[:MAXLEN]):
        x[j] = vocab.get(w, 1)
    return x


def main():
    import tensorflow as tf
    vocab = json.load(io.open(os.path.join(
        HERE, "trac_aggression_v1_vocab.json"), encoding="utf-8"))
    it = tf.lite.Interpreter(model_path=os.path.join(
        HERE, "trac_aggression_v1_float16.tflite"))
    it.allocate_tensors()
    inp, out = it.get_input_details()[0], it.get_output_details()[0]

    cases = {}
    for name, text in CASES.items():
        toks = tokenize(text)
        x = encode(text, vocab)
        it.set_tensor(inp["index"], x.reshape(1, MAXLEN).astype(np.int32))
        it.invoke()
        score = float(it.get_tensor(out["index"]).ravel()[0])
        cases[name] = {
            "text": text,
            "tokens": toks[:MAXLEN],
            "n_tokens_before_truncation": len(toks),
            "ids": [int(v) for v in x],
            "score": round(score, 6),
        }
        print("%-20s tok=%-3d score=%.4f" % (name, len(toks), score))

    doc = {
        "_generated_by": "work/trac_aggression/make_golden_trac.py",
        "_why": ("The Dart tokenizer and the trained model must agree "
                 "exactly. Produced by the same TOKEN_RE and the same "
                 ".tflite that scored 0.7081 on Indo-HateSpeech."),
        "_tokenizer": "lowercase, then [a-z0-9']+|[^\\x00-\\x7f]+",
        "_maxlen": MAXLEN,
        "_pad_index": 0,
        "_oov_index": 1,
        "_score_tolerance": ("1e-3; float16 tflite on a different runtime "
                             "is not bit-identical"),
        "cases": cases,
    }
    p = os.path.join(HERE, "trac_aggression_golden.json")
    io.open(p, "w", encoding="utf-8").write(
        json.dumps(doc, indent=2, ensure_ascii=False))
    print("\nwritten", p)


if __name__ == "__main__":
    main()
