import 'package:flutter/foundation.dart';
import 'package:tflite_flutter/tflite_flutter.dart' as tfl;

import '../models/inference_result.dart';
import 'gunshot_detector.dart' show GunshotDetectorV2;
import 'interpreter.dart';
import 'mel_spectrogram.dart';

/// Day 346 — `m_glass_breaking_v4`, the first detector in this project
/// shipped *because* it was measured rather than in spite of it.
///
/// WHY THIS SHIPS
/// --------------
/// It sat in `work/glass_retrain/` unshipped, carrying a recorded **AUC
/// 1.0 from 13 positives** — the same shape as the scream number that
/// collapsed on Day 345 (v3's 0.839 came from 45 positives and measured
/// 0.7675 on 287). That 1.0 did not survive either:
///
///     recorded   AUC 1.0000   (13 positives)
///     measured   AUC 0.7819   (265 positives, 95% CI [0.7344, 0.8292])
///
/// But 0.78 against hard negatives is a real detector, and its operating
/// curve is the best in this project:
///
/// | t | recall | precision |
/// |---|---|---|
/// | 0.60 | 0.491 | 0.922 |
/// | 0.51 | 0.566 | 0.882 |
/// | 0.41 | 0.626 | 0.856 |
/// | **0.22** | **0.826** | **0.830** |
///
/// For comparison the shipped scream detector manages 0.843 recall at
/// 0.282 precision, and gunshot 0.881 at 0.567. Glass-break is acoustically
/// distinctive — a short bright transient with a characteristic spectrum —
/// and it shows.
///
/// The negatives it was scored against are the confusable ones on purpose:
/// `Chink_and_clink` (168 clips), `Dishes_and_pots_and_pans` (48),
/// `Cutlery_and_silverware` (39). A dropped cutlery drawer should not read
/// as a broken window. See
/// `assets/models/DAY346B_GUNSHOT_GLASS_CROSS_CORPUS.md`.
///
/// CONTRACT — CLOSE TO GUNSHOT'S BUT NOT THE SAME
/// ----------------------------------------------
/// Read from `work/glass_retrain/train_glass.py` (`SR, DUR, N_MELS, N_FFT,
/// HOP, FMAX, IMG = 16000, 2.0, 96, 2048, 512, 8000, 96`), not inferred
/// from the tensor shape:
///
/// | | mg_gunshot_retrain | m_glass_breaking_v4 |
/// |---|---|---|
/// | Sample rate | 16,000 Hz | 16,000 Hz |
/// | Window | 3 s (48,000) | **2 s (32,000)** |
/// | Mel bands | 128 | **96** |
/// | Image | 128x128 | **96x96** |
/// | fmax | 8,000 Hz | 8,000 Hz |
/// | Input tensor | `[1,128,128,3]` (int8 or f32) | `[1,96,96,3]` **float32** |
///
/// The two differ in three of six fields, which is exactly why the shape is
/// not trusted to imply the rest — reading `[1,96,96,3]` and assuming
/// gunshot's 3 s window would feed the model 50% more audio than it has
/// ever seen and produce a confident wrong answer.
///
/// THE `np.resize` TRAP IS SHARED, SO THE IMPLEMENTATION IS TOO
/// -----------------------------------------------------------
/// Glass has the same post-mel step as gunshot and vehicle-crash:
/// `np.resize(mel_norm, (96, 96))`, which is **not** an image resize. It
/// flattens row-major and tiles/wraps once the source is exhausted; a real
/// 2 s clip yields a `[96, 63]` mel, so everything past column 63 repeats
/// earlier data. A bilinear resize here — the obvious reading of "resize a
/// spectrogram to an image" — gives the right shape and the wrong features.
///
/// So this reuses [GunshotDetectorV2.wrapResizeSquare] rather than adding a
/// fourth copy. That function is checked against
/// `test/fixtures/np_resize_wrap_golden.json`, generated by real
/// `numpy.resize`, so the parity guarantee carries over for free.
class GlassBreakDetector implements Interpreter {
  /// From `train_glass.py` `SR = 16000`.
  static const int kSampleRate = 16000;

  /// 2.0 s at [kSampleRate] — `DUR = 2.0`. **Not** gunshot's 3 s.
  static const int kSamples = 32000;

  static const int kMelBands = 96;
  static const int kImgSize = 96;
  static const int kChannels = 3;
  static const double kFmax = 8000.0;

  /// Flattened `[H][W][C]` row-major float count fed to [infer].
  static const int kInputFloats = kImgSize * kImgSize * kChannels; // 27,648

  /// Operating point, measured on 392 FSD50K eval clips (265 real `Glass`
  /// positives vs 127 hard negatives — clinking, dishes, cutlery, coins,
  /// bells) against the float16 export that ships.
  ///
  /// **0.22 is low on purpose and it is not the usual recall-vs-precision
  /// compromise.** On this curve 0.22 gives recall 0.826 at precision
  /// 0.830, while 0.41 gives 0.626 at 0.856. Dropping to 0.22 buys **+0.200
  /// recall for −0.026 precision** — almost free, because the score
  /// distribution is strongly bimodal. Going lower is untested and this
  /// should not be moved below 0.22 without re-measuring.
  ///
  /// Do not read this against the recorded `chosen_threshold: 0.8754` in
  /// `m_glass_breaking_v4_report.json`. That was picked on 13 positives,
  /// where it looked like a free 0.77 recall; on 265 positives the measured
  /// curve is already down to recall 0.283 by t=0.795, so at 0.8754 it is
  /// lower still. It is the clearest example in this project of a threshold
  /// chosen on an eval set too small to choose it.
  static const double kDefaultThreshold = 0.22;

  final tfl.Interpreter _interpreter;
  final MelSpectrogram _mel;
  final double threshold;

  @override
  final String modelLabel;

  GlassBreakDetector._({
    required tfl.Interpreter interpreter,
    required this.modelLabel,
    required this.threshold,
    MelSpectrogram? mel,
  })  : _interpreter = interpreter,
        _mel = mel ??
            MelSpectrogram(
              sampleRate: kSampleRate,
              nFft: 2048,
              hopLength: 512,
              nMels: kMelBands,
              fmax: kFmax,
            );

  @override
  int get expectedInputSize => kInputFloats;

  @override
  List<String> get classLabels => const ['normal', 'glass_break'];

  /// Loads the model, returning null on any failure so a device without it
  /// simply does not fire glass detections.
  ///
  /// The shape check is not ceremony: `[1,96,96,3]` is how this model is
  /// told apart from gunshot's `[1,128,128,3]`, and loading the wrong asset
  /// here would otherwise be silent.
  static Future<GlassBreakDetector?> tryLoad({
    String assetPath = 'assets/models/m_glass_breaking_v4.tflite',
    String modelLabel = 'm_glass_breaking_v4',
    double threshold = kDefaultThreshold,
  }) async {
    tfl.Interpreter? interpreter;
    try {
      interpreter = await tfl.Interpreter.fromAsset(assetPath);
      final inTensor = interpreter.getInputTensor(0);
      final outTensor = interpreter.getOutputTensor(0);

      const wantIn = [1, kImgSize, kImgSize, kChannels];
      if (!listEquals(inTensor.shape, wantIn)) {
        throw StateError('input shape ${inTensor.shape}, expected $wantIn');
      }
      if (outTensor.shape.fold<int>(1, (a, b) => a * b) != 1) {
        throw StateError(
            'output shape ${outTensor.shape}, expected a single scalar');
      }
      if (inTensor.type != tfl.TensorType.float32) {
        throw StateError('input dtype ${inTensor.type}, expected float32 '
            '(the shipped export is float16-quantized, which TFLite presents '
            'as float32)');
      }

      return GlassBreakDetector._(
        interpreter: interpreter,
        modelLabel: modelLabel,
        threshold: threshold,
      );
    } catch (e) {
      try {
        interpreter?.close();
      } catch (_) {}
      if (kDebugMode) {
        debugPrint('[GlassBreakDetector] tryLoad failed for $assetPath -> $e');
      }
      return null;
    }
  }

  /// Preferred entry point: raw mono PCM at [kSampleRate], any length.
  Future<InferenceResult> inferPcm(
    Float64List pcm, {
    required int timestampMs,
  }) =>
      infer(melImageFromPcm(pcm), timestampMs: timestampMs);

  /// Full preprocessing: fit to 2 s, mel spectrogram (96 bands, fmax 8000),
  /// dB with `ref=max`, per-clip min-max to `[0,1]`, `np.resize`-style wrap
  /// to 96x96, stacked into 3 identical channels, flattened row-major
  /// `[h][w][c]`.
  Float32List melImageFromPcm(Float64List pcm) {
    final clip = _fitSamples(pcm);
    final mel = _mel.compute(clip); // [96][~63] for a real 2 s / 16 kHz clip
    final img = GunshotDetectorV2.wrapResizeSquare(mel, kImgSize);

    final out = Float32List(kInputFloats);
    var i = 0;
    for (var h = 0; h < kImgSize; h++) {
      final row = img[h];
      for (var w = 0; w < kImgSize; w++) {
        final v = row[w];
        // 3 identical channels — np.stack([img] * 3, axis=-1).
        out[i++] = v;
        out[i++] = v;
        out[i++] = v;
      }
    }
    return out;
  }

  /// Pad with zeros or truncate to exactly [kSamples], from the start of the
  /// clip. The training script random-crops over-length clips; that is a
  /// training-time augmentation, not part of the learned input distribution,
  /// so inference is deterministic instead.
  static Float64List _fitSamples(Float64List pcm) {
    if (pcm.length == kSamples) return pcm;
    final out = Float64List(kSamples);
    final n = pcm.length < kSamples ? pcm.length : kSamples;
    out.setRange(0, n, pcm.length < kSamples ? pcm : pcm.sublist(0, kSamples));
    return out;
  }

  @override
  Future<InferenceResult> infer(
    Float32List features, {
    required int timestampMs,
  }) async {
    if (features.length != kInputFloats) {
      throw ArgumentError(
        'GlassBreakDetector expects $kInputFloats floats '
        '($kImgSize x $kImgSize x $kChannels image), got ${features.length}. '
        'Use inferPcm() if you are holding raw audio.',
      );
    }
    final t0 = DateTime.now();

    final input = features.reshape([1, kImgSize, kImgSize, kChannels]);
    final output = [Float32List(1)];
    _interpreter.run(input, output);
    final glass = output[0][0].toDouble().clamp(0.0, 1.0);

    final classScores = <String, double>{
      'normal': 1.0 - glass,
      'glass_break': glass,
    };
    final isGlass = glass >= threshold;

    return InferenceResult(
      label: isGlass ? 'glass_break' : 'normal',
      score: isGlass ? glass : 1.0 - glass,
      classScores: classScores,
      latencyMs: DateTime.now().difference(t0).inMilliseconds,
      timestampMs: timestampMs,
    );
  }

  @override
  Future<void> dispose() async {
    try {
      _interpreter.close();
    } catch (_) {
      // already closed
    }
  }
}
