import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show visibleForTesting;

/// Day 257 — librosa-compatible mel spectrogram, in Dart.
///
/// m1_scream_v2.tflite takes `[1, 128, 131, 1]` and was trained on features
/// produced by librosa. Anything structurally similar but numerically
/// different produces output of the right shape and range that the model
/// scores *wrongly* — a failure that looks exactly like a working pipeline.
/// So this is a deliberate reimplementation of librosa's defaults, verified
/// against golden values generated by librosa itself
/// (test/fixtures/mel_golden.json).
///
/// Two details that are easy to get wrong and silently ruin the output:
///
///  * **Slaney, not HTK.** librosa's mel scale defaults to Slaney (linear
///    below 1 kHz, log above) with `norm='slaney'` area normalisation. The
///    existing native `MfccExtractor.kt` uses the HTK formula
///    (`2595·log10(1 + f/700)`), which is a different filterbank entirely.
///  * **Periodic Hann, centred frames, ZERO padding.** librosa uses a
///    periodic (not symmetric) Hann window and pads the signal by
///    `nFft ~/ 2` so frame *t* is centred on sample `t * hop`. The pad is
///    **zeros**: `librosa.stft`'s default `pad_mode` changed from
///    `'reflect'` to `'constant'` in librosa 0.10. Reflect-padding is
///    numerically correct code that produces the wrong answer here — it
///    only moves the first and last two frames, so every structural test
///    still passes. See `_centrePad`.
///
/// Parameters come from `m1_train_v2.py`, confirmed against the training
/// notebook — see assets/models/PREPROCESSING_SPEC.md.
class MelSpectrogram {
  /// [fmax] mirrors librosa's `fmax` kwarg to `librosa.feature.melspectrogram`
  /// / `librosa.filters.mel`: it caps the top edge of the mel filterbank,
  /// independent of the FFT's own Nyquist bound (`sampleRate / 2`), which is
  /// always used for the underlying FFT bin frequencies. Defaults to
  /// `sampleRate / 2` (librosa's own default) when omitted — this is what
  /// m1_scream_v2 uses. mg_gunshot's retrain passes `fmax=8000` explicitly
  /// (see `day261_mg_gunshot_retrain.py`), which is why this exists.
  MelSpectrogram({
    this.sampleRate = 22050,
    this.nFft = 2048,
    this.hopLength = 512,
    this.nMels = 128,
    double? fmax,
  })  : fmax = fmax ?? sampleRate / 2.0,
        _filterbank = _buildSlaneyFilterbank(
            sampleRate, nFft, nMels, fmax ?? sampleRate / 2.0),
        _window = _periodicHann(nFft),
        _twiddleCos = _twiddleTable(nFft, math.cos),
        _twiddleSin = _twiddleTable(nFft, math.sin);

  final int sampleRate;
  final int nFft;
  final int hopLength;
  final int nMels;
  final double fmax;

  final List<Float64List> _filterbank; // [nMels][1 + nFft/2]
  final Float64List _window;

  /// `exp(-2*pi*i*j/nFft)` for `j` in `[0, nFft/2)`, split into real and
  /// imaginary parts. A butterfly of span `len` wants `exp(-2*pi*i*k/len)`,
  /// which is entry `k * nFft ~/ len`.
  final Float64List _twiddleCos;
  final Float64List _twiddleSin;

  int get _bins => nFft ~/ 2 + 1;

  /// Mel spectrogram in dB, min-max normalised to [0, 1] by default.
  ///
  /// Returns `[nMels][frames]`, matching the training pipeline's
  /// `power_to_db(mel, ref=max)` followed by per-clip min-max scaling.
  ///
  /// Pass [normalize] = false to get `power_to_db(mel, ref=max)` alone, with
  /// no min-max rescale — this is what `s_crowd_panic`'s `audio_to_mel`
  /// (`day95_s_crowd_panic.py`) does: it pads/crops the raw dB spectrogram to
  /// a fixed shape and lets a separate *global* mean/std step (`mel_mean`/
  /// `mel_std` in `s_crowd_panic_norm.json`) handle scaling, unlike
  /// m1_scream_v2/mg_gunshot's *per-clip* min-max. Reusing the default
  /// (normalize: true) path for `s_crowd_panic` would silently double-
  /// normalise and feed the model values it never saw in training.
  List<Float64List> compute(Float64List samples, {bool normalize = true}) {
    final power = _stftPower(samples);          // [frames][bins]
    final frames = power.length;

    // mel = filterbank @ power
    final mel = List<Float64List>.generate(nMels, (_) => Float64List(frames));
    for (var m = 0; m < nMels; m++) {
      final fb = _filterbank[m];
      final row = mel[m];
      for (var t = 0; t < frames; t++) {
        final spec = power[t];
        var acc = 0.0;
        for (var k = 0; k < _bins; k++) {
          final w = fb[k];
          if (w != 0.0) acc += w * spec[k];
        }
        row[t] = acc;
      }
    }

    return normalize ? _powerToDbNormalised(mel) : _powerToDb(mel);
  }

  /// Pads or trims the mel to exactly [targetFrames] columns.
  ///
  /// The training script yields 130 frames for a 3 s clip while the exported
  /// model expects 131. Measured impact of the padding choice is at most
  /// 0.0195 on real audio, so zero-padding is fine — see the spec doc.
  static List<Float64List> fitFrames(List<Float64List> mel, int targetFrames) {
    if (mel.isEmpty || mel[0].length == targetFrames) return mel;
    return [
      for (final row in mel)
        Float64List(targetFrames)
          ..setRange(0, math.min(row.length, targetFrames),
              row.length >= targetFrames ? row.sublist(0, targetFrames) : row),
    ];
  }

  /// Test-only: raw power spectrum of one frame, for librosa parity checks.
  @visibleForTesting
  Float64List debugFramePower(Float64List y, int frame) => _stftPower(y)[frame];

  // ── STFT ────────────────────────────────────────────────────────────────

  /// `|STFT|^2` with centred frames, matching librosa's `center=True`.
  List<Float64List> _stftPower(Float64List y) {
    final pad = nFft ~/ 2;
    final padded = _centrePad(y, pad);
    final frames = 1 + (padded.length - nFft) ~/ hopLength;

    final out = <Float64List>[];
    final re = Float64List(nFft);
    final im = Float64List(nFft);

    for (var f = 0; f < frames; f++) {
      final start = f * hopLength;
      for (var i = 0; i < nFft; i++) {
        re[i] = padded[start + i] * _window[i];
        im[i] = 0.0;
      }
      _fftInPlace(re, im);
      final spec = Float64List(_bins);
      for (var k = 0; k < _bins; k++) {
        spec[k] = re[k] * re[k] + im[k] * im[k]; // power, not magnitude
      }
      out.add(spec);
    }
    return out;
  }

  /// `np.pad(y, nFft // 2, mode='constant')` — librosa's `center=True`
  /// padding since 0.10.
  ///
  /// This must stay zeros. Reflect padding is what an older librosa did and
  /// what the obvious reading of "centred frames" suggests, but it changes
  /// only the two frames at each end — which no shape, range, or
  /// monotonicity check can see. The parity fixture is the only thing that
  /// distinguishes them.
  static Float64List _centrePad(Float64List y, int pad) {
    final out = Float64List(y.length + 2 * pad); // Float64List is zero-filled
    out.setRange(pad, pad + y.length, y);
    return out;
  }

  static Float64List _twiddleTable(int n, double Function(double) fn) {
    final t = Float64List(n ~/ 2);
    for (var j = 0; j < t.length; j++) {
      t[j] = fn(-2 * math.pi * j / n);
    }
    return t;
  }

  /// Iterative radix-2 FFT. [nFft] must be a power of two (2048 here).
  void _fftInPlace(Float64List re, Float64List im) {
    final n = re.length;
    for (var i = 1, j = 0; i < n; i++) {
      var bit = n >> 1;
      for (; j & bit != 0; bit >>= 1) {
        j ^= bit;
      }
      j ^= bit;
      if (i < j) {
        var t = re[i]; re[i] = re[j]; re[j] = t;
        t = im[i]; im[i] = im[j]; im[j] = t;
      }
    }
    for (var len = 2; len <= n; len <<= 1) {
      final half = len ~/ 2;
      final stride = n ~/ len;
      for (var i = 0; i < n; i += len) {
        for (var k = 0; k < half; k++) {
          // Twiddles come from a precomputed table, not a running recurrence.
          // The recurrence version produced an erratic spectrum (dips where
          // the tone's peak should be) — caught by the librosa parity test,
          // not by any structural check. The table keeps each twiddle an
          // independent `cos`/`sin` evaluation while removing ~1.4M trig
          // calls per 3 s window from the audio path.
          final cr = _twiddleCos[k * stride], ci = _twiddleSin[k * stride];
          final ur = re[i + k], ui = im[i + k];
          final xr = re[i + k + half], xi = im[i + k + half];
          final vr = xr * cr - xi * ci;
          final vi = xr * ci + xi * cr;
          re[i + k] = ur + vr; im[i + k] = ui + vi;
          re[i + k + half] = ur - vr; im[i + k + half] = ui - vi;
        }
      }
    }
  }

  /// Periodic Hann — librosa/scipy use `sym=False`.
  static Float64List _periodicHann(int n) {
    final w = Float64List(n);
    for (var i = 0; i < n; i++) {
      w[i] = 0.5 - 0.5 * math.cos(2 * math.pi * i / n);
    }
    return w;
  }

  // ── dB conversion ───────────────────────────────────────────────────────

  /// `librosa.power_to_db(S, ref=np.max)` then min-max to [0, 1].
  ///
  /// librosa clamps at `amin = 1e-10` and floors the result at
  /// `max - top_db` with `top_db = 80`; both matter, because the floor sets
  /// the minimum used by the normalisation that follows.
  static List<Float64List> _powerToDbNormalised(List<Float64List> mel) {
    const amin = 1e-10, topDb = 80.0;

    var maxPower = amin;
    for (final row in mel) {
      for (final v in row) {
        if (v > maxPower) maxPower = v;
      }
    }
    final refDb = 10.0 * _log10(math.max(amin, maxPower));

    var maxDb = double.negativeInfinity;
    final db = <Float64List>[];
    for (final row in mel) {
      final r = Float64List(row.length);
      for (var i = 0; i < row.length; i++) {
        r[i] = 10.0 * _log10(math.max(amin, row[i])) - refDb;
        if (r[i] > maxDb) maxDb = r[i];
      }
      db.add(r);
    }

    final floor = maxDb - topDb;
    var lo = double.infinity, hi = double.negativeInfinity;
    for (final row in db) {
      for (var i = 0; i < row.length; i++) {
        if (row[i] < floor) row[i] = floor;
        if (row[i] < lo) lo = row[i];
        if (row[i] > hi) hi = row[i];
      }
    }

    final span = hi - lo + 1e-9;
    for (final row in db) {
      for (var i = 0; i < row.length; i++) {
        row[i] = (row[i] - lo) / span;
      }
    }
    return db;
  }

  /// `librosa.power_to_db(S, ref=np.max)` with the standard `top_db=80`
  /// floor, but **no** min-max rescale — used by `s_crowd_panic`, whose
  /// normalisation is a separate global mean/std step applied by the caller.
  static List<Float64List> _powerToDb(List<Float64List> mel) {
    const amin = 1e-10, topDb = 80.0;

    var maxPower = amin;
    for (final row in mel) {
      for (final v in row) {
        if (v > maxPower) maxPower = v;
      }
    }
    final refDb = 10.0 * _log10(math.max(amin, maxPower));

    var maxDb = double.negativeInfinity;
    final db = <Float64List>[];
    for (final row in mel) {
      final r = Float64List(row.length);
      for (var i = 0; i < row.length; i++) {
        r[i] = 10.0 * _log10(math.max(amin, row[i])) - refDb;
        if (r[i] > maxDb) maxDb = r[i];
      }
      db.add(r);
    }

    final floor = maxDb - topDb;
    for (final row in db) {
      for (var i = 0; i < row.length; i++) {
        if (row[i] < floor) row[i] = floor;
      }
    }
    return db;
  }

  static double _log10(double x) => math.log(x) / math.ln10;

  // ── Slaney mel filterbank ───────────────────────────────────────────────

  static double _hzToMel(double hz) {
    const fSp = 200.0 / 3.0;
    const minLogHz = 1000.0;
    final minLogMel = minLogHz / fSp;
    final logstep = math.log(6.4) / 27.0;
    if (hz < minLogHz) return hz / fSp;
    return minLogMel + math.log(hz / minLogHz) / logstep;
  }

  static double _melToHz(double mel) {
    const fSp = 200.0 / 3.0;
    const minLogHz = 1000.0;
    final minLogMel = minLogHz / fSp;
    final logstep = math.log(6.4) / 27.0;
    if (mel < minLogMel) return fSp * mel;
    return minLogHz * math.exp(logstep * (mel - minLogMel));
  }

  /// `librosa.filters.mel(sr, n_fft, n_mels, fmax=fmax, norm='slaney',
  /// htk=False)`.
  ///
  /// [fmax] caps the top mel edge; the FFT bin frequencies ([fftFreqs])
  /// always run to the true Nyquist (`sr / 2`) regardless of [fmax] — this
  /// matches librosa, where `fmax` only affects `mel_f`, not `fftfreqs`.
  static List<Float64List> _buildSlaneyFilterbank(
      int sr, int nFft, int nMels, double fmax) {
    final bins = nFft ~/ 2 + 1;
    final nyquist = sr / 2.0;

    final fftFreqs = Float64List(bins);
    for (var k = 0; k < bins; k++) {
      fftFreqs[k] = nyquist * k / (bins - 1);
    }

    // n_mels + 2 edge points, evenly spaced on the mel scale up to fmax.
    final melMax = _hzToMel(fmax);
    final melF = Float64List(nMels + 2);
    for (var i = 0; i < nMels + 2; i++) {
      melF[i] = _melToHz(melMax * i / (nMels + 1));
    }

    final weights = List<Float64List>.generate(nMels, (_) => Float64List(bins));
    for (var m = 0; m < nMels; m++) {
      final lowerEdge = melF[m], centre = melF[m + 1], upperEdge = melF[m + 2];
      final dLower = centre - lowerEdge, dUpper = upperEdge - centre;
      // Slaney area normalisation: equal energy per band regardless of width.
      final enorm = 2.0 / (upperEdge - lowerEdge);
      for (var k = 0; k < bins; k++) {
        final f = fftFreqs[k];
        final lower = dLower == 0 ? 0.0 : (f - lowerEdge) / dLower;
        final upper = dUpper == 0 ? 0.0 : (upperEdge - f) / dUpper;
        final w = math.min(lower, upper);
        weights[m][k] = w > 0 ? w * enorm : 0.0;
      }
    }
    return weights;
  }
}
