import 'dart:math' as math;
import 'dart:typed_data';

import 'mel_spectrogram.dart';

/// Day 325 — the 28-dim prosodic vector `m5_vocal_stress_v2` takes.
///
/// ## Why 28 and not the 38 the training script defines
///
/// `day95_m5_vocal_stress_apac.py` builds a 38-dim vector, but 10 of those
/// need DSP this app does not have: 5 from `librosa.pyin` (probabilistic YIN
/// pitch tracking), 4 from an RMS series, 1 from autocorrelation. Rather than
/// implement pyin in Dart, their value was measured first, on an identical
/// held-out-speaker split:
///
///     all 38 features                   AUC 0.7986
///     these 28                          AUC 0.7988   <- no measurable loss
///     only the 10 dropped               AUC 0.5620   (near chance)
///
/// So the pitch features carry nothing this model needs, and the version that
/// ships is the one the app can actually feed. That measurement is the whole
/// justification for this class existing in this shape.
///
/// ## Why not reuse the native 15-scalar feature stream
///
/// `lib/native/audio_features.dart` already ships MFCCs from Kotlin, which
/// looks like a shortcut. It is not: `MfccExtractor.kt` runs at
/// **sr 22,050 / FFT 8192**, while this model's features come from librosa at
/// **sr 16,000 / n_fft 512 / hop 256**. Those are different quantities that
/// happen to share a name. Feeding one to a model trained on the other gives
/// the right tensor shape, plausible values, and wrong answers — the same
/// failure that had `scream_classifier_v1` claiming 0.95 recall while firing
/// on 5.6% of real screams.
///
/// ## Feature order — load-bearing
///
///     [ 0..12]  mfcc_mean[0..12]
///     [13..25]  mfcc_std[0..12]
///     [26]      zcr                 mean zero-crossing rate
///     [27]      spectral_centroid   mean centroid Hz **÷ (sr/2)**
///
/// That last division is easy to miss and would shift one feature by ~8000×.
///
/// Parity is pinned by `test/vocal_stress_features_test.dart` against
/// `test/fixtures/m5_vocal_stress_golden.json`, generated by real librosa.
class VocalStressFeatures {
  /// Model sample rate. Audio at any other rate must be resampled first.
  static const int kSampleRate = 16000;

  /// 3.0 s at [kSampleRate]. Shorter is zero-padded, longer truncated.
  static const int kSamples = 48000;

  static const int kNMfcc = 13;
  static const int kNFft = 512;
  static const int kHopLength = 256;
  static const int kNMels = 128;

  /// 13 means + 13 stds + zcr + centroid.
  static const int kFeatureDim = 2 * kNMfcc + 2; // 28

  VocalStressFeatures({MelSpectrogram? mel})
      : _mel = mel ??
            MelSpectrogram(
              sampleRate: kSampleRate,
              nFft: kNFft,
              hopLength: kHopLength,
              nMels: kNMels,
              // librosa's melspectrogram default is fmax = sr/2.
              fmax: kSampleRate / 2,
            );

  final MelSpectrogram _mel;

  /// Raw mono PCM at [kSampleRate] -> the model's 28 floats.
  ///
  /// Returns physical (un-standardised) values. The caller applies the
  /// mean/std from `assets/models/m5_vocal_stress_v2_norm.json`; skipping
  /// that step does not throw and does not change the shape, it just makes
  /// the model wrong.
  Float64List extract(Float64List pcm) {
    final clip = _fit(pcm);
    final m = _mel.mfcc(clip, nMfcc: kNMfcc); // [13][frames]
    final out = Float64List(kFeatureDim);

    for (var k = 0; k < kNMfcc; k++) {
      final row = m[k];
      if (row.isEmpty) continue;
      var sum = 0.0;
      for (final v in row) {
        sum += v;
      }
      final mean = sum / row.length;
      var sq = 0.0;
      for (final v in row) {
        final d = v - mean;
        sq += d * d;
      }
      out[k] = mean;
      // Population std (ddof=0) — numpy's default, which librosa's callers use.
      out[kNMfcc + k] = math.sqrt(sq / row.length);
    }

    out[2 * kNMfcc] = _zeroCrossingRate(clip);
    out[2 * kNMfcc + 1] = _spectralCentroidOverNyquist(clip);
    return out;
  }

  /// Day 332 — the five of the ten missing 38-vector features that need no
  /// `pyin`.
  ///
  /// In the day95 38-feature vector these sit at `[5]` shimmer, `[6]` hnr,
  /// `[33]` rms_mean, `[34]` rms_std, `[35]` rms_max. The other five
  /// (`[0..4]`: voiced_frac, f0_mean, f0_std, f0_range, jitter) all come from
  /// `librosa.pyin` and are deliberately **not** implemented — measured on
  /// held-out speakers, these five are worth +0.052 AUC in English for the
  /// arithmetic below, while pyin is worth a further +0.110 for a difference
  /// function, cumulative mean normalisation, thresholding, parabolic
  /// interpolation and a Viterbi pass. See
  /// `assets/models/DAY332_M7_M3_PYIN.md`.
  ///
  /// [extract] is deliberately left at 28 so the shipped
  /// `m5_vocal_stress_v2` keeps its exact input; compose these alongside it
  /// when a 33-feature model ships.
  ///
  /// Order matches the 38-vector: `[shimmer, hnr, rms_mean, rms_std, rms_max]`.
  Float64List extendedFeatures(Float64List pcm) {
    final clip = _fit(pcm);
    final rms = rmsFrames(clip);
    final out = Float64List(5);
    out[0] = _meanAbsDiff(rms);
    out[1] = _harmonicsToNoise(clip);
    var sum = 0.0, max = 0.0;
    for (final v in rms) {
      sum += v;
      if (v > max) max = v;
    }
    final mean = rms.isEmpty ? 0.0 : sum / rms.length;
    var sq = 0.0;
    for (final v in rms) {
      final d = v - mean;
      sq += d * d;
    }
    out[2] = mean;
    out[3] = rms.isEmpty ? 0.0 : math.sqrt(sq / rms.length);
    out[4] = max;
    return out;
  }

  /// `librosa.feature.rms(y, frame_length: kNFft, hop_length: kHopLength)`.
  ///
  /// librosa defaults to `center=True` with `'constant'` (zero) padding of
  /// `frame_length ~/ 2` each side, which yields `1 + y.length ~/ hop`
  /// frames — 188 for a 48,000-sample clip. Per frame the value is
  /// `sqrt(mean(x^2))`, **not** `mean(abs(x))`.
  ///
  /// Verified against librosa 0.10.2 to 1.2e-8 on a real ESD clip before this
  /// was ported; that residual is float32-vs-float64 accumulation, not a
  /// difference in framing.
  static Float64List rmsFrames(Float64List y) {
    const half = kNFft ~/ 2;
    final padded = Float64List(y.length + 2 * half);
    padded.setRange(half, half + y.length, y);

    final frames = 1 + (y.length ~/ kHopLength);
    final out = Float64List(frames);
    var n = 0;
    for (var f = 0; f < frames; f++) {
      final start = f * kHopLength;
      if (start + kNFft > padded.length) break;
      var sq = 0.0;
      for (var i = 0; i < kNFft; i++) {
        final v = padded[start + i];
        sq += v * v;
      }
      out[n++] = math.sqrt(sq / kNFft);
    }
    return n == frames ? out : Float64List.sublistView(out, 0, n);
  }

  static double _meanAbsDiff(Float64List v) {
    if (v.length < 2) return 0.0;
    var sum = 0.0;
    for (var i = 1; i < v.length; i++) {
      sum += (v[i] - v[i - 1]).abs();
    }
    return sum / (v.length - 1);
  }

  /// `clip(max(ac[1:int(sr*0.02)]) / ac[0], 0, 1)` where `ac` is the
  /// self-correlation kept from its centre.
  ///
  /// Two details that matter: this runs on the **unpadded** signal, unlike
  /// [rmsFrames], and the lag window stops at `int(sr * 0.02)` = 320 samples
  /// (20 ms, i.e. down to 50 Hz). Only lags `1..319` are searched, so lag 0 —
  /// which is by definition the maximum — is excluded.
  static double _harmonicsToNoise(Float64List y) {
    final maxLag = (kSampleRate * 0.02).toInt();
    final limit = maxLag < y.length ? maxLag : y.length;
    var zero = 0.0;
    for (final v in y) {
      zero += v * v;
    }
    var best = 0.0;
    for (var lag = 1; lag < limit; lag++) {
      var acc = 0.0;
      for (var i = 0; i + lag < y.length; i++) {
        acc += y[i] * y[i + lag];
      }
      if (acc > best) best = acc;
    }
    final r = best / (zero + 1e-8);
    return r < 0.0 ? 0.0 : (r > 1.0 ? 1.0 : r);
  }

  static Float64List _fit(Float64List pcm) {
    if (pcm.length == kSamples) return pcm;
    final out = Float64List(kSamples);
    final n = pcm.length < kSamples ? pcm.length : kSamples;
    out.setRange(0, n, pcm);
    return out;
  }

  /// `librosa.feature.zero_crossing_rate(y, frame_length, hop_length).mean()`.
  ///
  /// librosa centre-pads by `frame_length ~/ 2` with `'constant'` (zeros) and
  /// reports, per frame, the fraction of positions where `sign` changes —
  /// counting a zero sample as positive, which is what `np.signbit` does.
  static double _zeroCrossingRate(Float64List y) {
    const half = kNFft ~/ 2;
    final padded = Float64List(y.length + 2 * half);
    padded.setRange(half, half + y.length, y);

    final frames = 1 + (y.length ~/ kHopLength);
    var total = 0.0;
    var counted = 0;
    for (var f = 0; f < frames; f++) {
      final start = f * kHopLength;
      if (start + kNFft > padded.length) break;
      var crossings = 0;
      var prevNeg = padded[start] < 0;
      for (var i = 1; i < kNFft; i++) {
        final neg = padded[start + i] < 0;
        if (neg != prevNeg) crossings++;
        prevNeg = neg;
      }
      total += crossings / kNFft;
      counted++;
    }
    return counted == 0 ? 0.0 : total / counted;
  }

  /// `librosa.feature.spectral_centroid(...).mean() / (sr / 2)`.
  ///
  /// librosa weights by the **magnitude** spectrum, not power — `S =
  /// |stft(y)|`. Using power here would bias the centroid upward on every
  /// frame.
  double _spectralCentroidOverNyquist(Float64List y) {
    final power = _mel.stftPowerForCentroid(y); // [frames][bins]
    if (power.isEmpty) return 0.0;
    final bins = power[0].length;
    final freqs = Float64List(bins);
    for (var k = 0; k < bins; k++) {
      freqs[k] = k * kSampleRate / kNFft;
    }
    var sum = 0.0;
    var frames = 0;
    for (final spec in power) {
      var num = 0.0, den = 0.0;
      for (var k = 0; k < bins; k++) {
        final mag = math.sqrt(spec[k]); // power -> magnitude
        num += freqs[k] * mag;
        den += mag;
      }
      sum += den == 0.0 ? 0.0 : num / den;
      frames++;
    }
    final mean = frames == 0 ? 0.0 : sum / frames;
    return mean / (kSampleRate / 2);
  }
}
