"""Day 352 - golden fixture for the Dart AggressiveSpeechFeatures path.

Generated by THE SAME features38() that produced v4's training data, so a
Dart mismatch is a Dart bug and not a spec disagreement. Without this the
2048/512 path would be unverified, which is exactly how m4 ended up able to
report DEAD at a constant 1.0 on the wrong fixture.
"""
import io, json, os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from featurise_yin2048 import features38, SR, NEED, FRAME, HOP

def tone(sec=3.0):
    n = int(SR * sec)
    t = np.arange(n) / SR
    return 0.5*np.sin(2*np.pi*220*t) + 0.25*np.sin(2*np.pi*660*t)

def main():
    import librosa
    sigs = {
        "tone": tone(),
        "noise": np.random.RandomState(0).randn(NEED) * 0.1,
        "silence": np.zeros(NEED),
        "short": tone(0.4),
    }
    out = {"frame": FRAME, "hop": HOP, "sr": SR,
           "note": "from featurise_yin2048.features38 -- the v4 trainer",
           "cases": {}}
    for name, y in sigs.items():
        f = features38(np.asarray(y, np.float64), librosa)
        out["cases"][name] = [round(float(v), 8) for v in f]
        print(f"{name:8s} f0_mean={f[1]:9.3f} shimmer={f[5]:.6f} "
              f"hnr={f[6]:.6f} mfcc0={f[7]:9.3f} zcr={f[36]:.6f}")
    dst = (r"C:\Users\hridy\Desktop\zapsafe\letsstartbuilding"
           r"\zapsafe_mobile_main_reconcile\test\fixtures"
           r"\h_aggressive_v4_golden.json")
    json.dump(out, io.open(dst, "w", encoding="utf-8"), indent=1)
    print("wrote", dst)

if __name__ == "__main__":
    main()
